<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Tunnels;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('tunnel_create')]
#[Description(<<<'MARKDOWN'
    Attach a public tunnel hostname to a domain

    Registers a public hostname that reaches this domain without any DNS record of your own. The `panelalpha` provider allocates a name under panelalpha.online through the licensing proxy -- the way to give an application a public address with a trusted certificate on an engine with no DNS of its own. Attach it to the project domain of the same name: the proxy forwards with `Host: <the domain the tunnel is attached to>`, so a panelalpha hostname on any other local domain leaves the application answering under a name nobody typed, and anything that canonicalises its own site URL redirects for ever. Labels are first come, first served across the fleet, so a name in use is refused; deleting the tunnel releases it again. `cloudflare` puts a CNAME in a zone the project's own API token controls, so it fits a custom domain; set the token first with PUT /projects/{username}/settings/cloudflare-api-token.
    MARKDOWN)]
#[IsDestructive]
class TunnelCreateTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/domains/{domain}/tunnels';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
            'domain',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'hostname',
            'provider',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'domain' => $schema->string()->required(),
            'hostname' => $schema->string()->description('The public hostname to attach. For the panelalpha provider it must be a single label under panelalpha.online, and must equal the domain it is attached to. Example: my-shop.panelalpha.online.')->required(),
            'provider' => $schema->string()->description('Defaults to panelalpha. One of: cloudflare, panelalpha. Example: panelalpha.'),
        ];
    }
}
