<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\SecretVault;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('vault_config_get')]
#[Description(<<<'MARKDOWN'
    Which global secrets are stored

    Lists the global entries that have a secret pasted, as `globals` (ref, type, purpose). Any project may use one by passing its `vault:<id>`; nothing uses one unasked.

    Calls GET /api/vault/config.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class VaultConfigGetTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/vault/config';
    }



    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [];
    }
}
