<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\SecretVault;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('vault_secret_create')]
#[Description(<<<'MARKDOWN'
    Create a vault slot for a secret that will be pasted in a browser

    Mints a paste slot. Returns `ref` (`vault:<id>`, pass it where the secret would go -- e.g. the `git_token` field of project_create) and `url` (the form the customer opens and pastes the secret into, open for `url_expires_in` seconds). The secret expires only if `expires_in` is given; it is then refused and deleted automatically. **The secret never passes through the API caller** -- that is this mechanism's whole purpose, for agents that must not relay a private-repository token through a conversation. `scope` decides where it may be used: `project` (the default) belongs to the first project it is given to and is refused everywhere else; `global` may be used by any project that names it. Nothing uses a secret unasked. Give `purpose` so the entry can be recognised later: the secret is never readable again, so the listing is all you have. **A pasted secret is final** -- to replace one, delete it and create a new link. The form checks a `git_token` or `cloudflare_api_token` before saving it, with the same calls the engine makes when it uses one: a git token against `verify_with.repo_url` (required for the check), a Cloudflare token for its account and Tunnel access, plus the zone of `verify_with.hostname` when given. A refused token is not stored and the link stays open. `verification` on status then says whether it was checked.
    MARKDOWN)]
#[IsDestructive]
class VaultSecretCreateTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/vault/secrets';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'type',
            'scope',
            'expires_in',
            'project',
            'purpose',
            'verify_with',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'type' => $schema->string()->description('The request field the reference will be passed in (e.g. `git_token`, `env_vars`). Free-form snake_case -- the field the caller will send `vault:<id>` in. The paste form shows help from `resources/vault/<type>.md` when that file exists, else the default help. Example: git_token.')->required(),
            'scope' => $schema->string()->description('`project` (the default): usable by one project only -- the first one it is given to claims it, and any other project is refused. `global`: usable by any project that names it. Either way it is used only where a request passes its `vault:<id>`, and there may be any number of each type. One of: project, global.'),
            'expires_in' => $schema->integer()->description('Seconds until the secret expires. After that it is refused and deleted, with no one having to remove it. Omitted, it never expires. A project that already used the secret keeps the copy it stored.'),
            'project' => $schema->string()->description('Only with `scope: project`: the project that owns the secret from the start, so only that project can read it. The project need not exist yet. Omitted, the first project that reads the secret owns it. Example: shop.'),
            'purpose' => $schema->string()->description('What this secret is for, in your words -- "deploy key for the shop repo", "Cloudflare token for the staging zone". Shown on the paste form, so the person handing over a credential can see why, and returned by `list`. Several entries share one `type`, and the secret can never be read back, so this is what tells them apart later when deciding which to delete. Example: Deploy key for the shop repo.'),
            'verify_with' => $schema->object()->description('What the pasted secret is checked against before it is saved. `git_token`: `repo_url`, the HTTPS repository the token must be able to read. `cloudflare_api_token`: `hostname` (optional), a domain whose zone the token must see. A refused token is not stored and the form asks again; an unreachable host saves it unchecked.'),
        ];
    }
}
