<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\SecretVault;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('vault_config_get')]
#[Description(<<<'MARKDOWN'
    Whether projects share the engine-wide secrets

    Reports `project_scoped_tokens`. False (the default) means a project created without a Git or Cloudflare token uses the engine-wide one, if a `global` vault entry holds it.

    Calls GET /api/vault/config.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class VaultConfigGetTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/vault/config';
    }



    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [];
    }
}
