<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\SecretVault;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;

#[Name('vault_secret_delete')]
#[Description(<<<'MARKDOWN'
    Delete a vault entry

    Removes the entry and its secret. References to it stop resolving. This is also how a secret is *replaced*: a stored secret can never be overwritten, so delete it and create a new one. `ref` accepts the `vault:<id>` create returned, `global:<type>` for an engine-wide secret, or `id:<n>` from `list`.

    Calls DELETE /api/vault/secrets/{ref}. This changes server state.
    MARKDOWN)]
#[IsDestructive]
#[IsIdempotent]
class VaultSecretDeleteTool extends ApiTool
{
    protected function method(): string
    {
        return 'DELETE';
    }

    protected function path(): string
    {
        return '/vault/secrets/{ref}';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'ref',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'ref' => $schema->string()->required(),
        ];
    }
}
