<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\SecretVault;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('vault_secret_status')]
#[Description(<<<'MARKDOWN'
    Get one vault entry by its reference

    The status of one entry. `ref` is the full `vault:<id>` value `create` returned, `global:<type>` for an engine-wide secret, or `id:<n>` from `list`. The secret is never included.

    Calls GET /api/vault/secrets/{ref}.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class VaultSecretStatusTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/vault/secrets/{ref}';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'ref',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'ref' => $schema->string()->required(),
        ];
    }
}
