<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\SecretVault;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('vault_secret_list')]
#[Description(<<<'MARKDOWN'
    List vault entries

    Every live or recently expired entry, newest first. **The secret is never included** and cannot be read back by any endpoint -- this is the inventory, not the values. Each row carries `id` (pass as `id:<n>` to status or delete), `type`, `purpose`, `scope`, `status` (pending, filled or expired) and the dates. `purpose` is what tells two entries of the same type apart when deciding which to delete.

    Calls GET /api/vault/secrets.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class VaultSecretListTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/vault/secrets';
    }

    /**
     * @return array<int, string>
     */
    protected function queryParams(): array
    {
        return [
            'type',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'type' => $schema->string()->description('Only entries of this type.'),
        ];
    }
}
