<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\SecretVault;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;

#[Name('vault_config_set')]
#[Description(<<<'MARKDOWN'
    Turn engine-wide secret sharing on or off

    Set `project_scoped_tokens` true to keep every project on the credentials it was given: global entries stay stored but nothing reaches for them on a project's behalf, which is what a multi-customer engine wants. False (the default) shares them. Existing projects are not rewritten either way -- this only decides what a project *without* its own credential falls back to, so the switch can be flipped back.

    Calls PUT /api/vault/config. This changes server state.
    MARKDOWN)]
#[IsDestructive]
#[IsIdempotent]
class VaultConfigSetTool extends ApiTool
{
    protected function method(): string
    {
        return 'PUT';
    }

    protected function path(): string
    {
        return '/vault/config';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'project_scoped_tokens',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'project_scoped_tokens' => $schema->boolean()->required(),
        ];
    }
}
