<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Usage;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('domain_bandwidth')]
#[Description(<<<'MARKDOWN'
    Get bandwidth time series for a domain

    Values are bytes. Missing AWStats data is an empty object, not an error.

    Calls GET /api/projects/{username}/domains/{domain}/bandwidth.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class DomainBandwidthTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/projects/{username}/domains/{domain}/bandwidth';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
            'domain',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function queryParams(): array
    {
        return [
            'start',
            'end',
            'group_by',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('Name of the project. Sent to the API as `username`.')->required(),
            'domain' => $schema->string()->required(),
            'start' => $schema->string()->description('Example: 2026-09-01.')->required(),
            'end' => $schema->string()->description('Example: 2026-09-30.')->required(),
            'group_by' => $schema->string()->description('One of: day, month.')->required(),
        ];
    }
}
