<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Usage;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('domain_visitors_breakdown')]
#[Description(<<<'MARKDOWN'
    Get a visitor breakdown for a domain

    Breakdown visits are the hits/visits from the AWStats section for every calendar month overlapping start/end; they are not clipped to the day range. Geo dimensions (countries, continents, regions) are empty until `geolocation:database update` has stored a local City MMDB. Device and device-brand are not implemented.

    Calls GET /api/projects/{username}/domains/{domain}/visitors/{dimension}.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class DomainVisitorsBreakdownTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/projects/{username}/domains/{domain}/visitors/{dimension}';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
            'domain',
            'dimension',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function queryParams(): array
    {
        return [
            'start',
            'end',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('Name of the project. Sent to the API as `username`.')->required(),
            'domain' => $schema->string()->required(),
            'dimension' => $schema->string()->description('One of: pages, countries, continents, regions, referrers, os, browsers.')->required(),
            'start' => $schema->string()->description('Example: 2026-09-01.')->required(),
            'end' => $schema->string()->description('Example: 2026-09-30.')->required(),
        ];
    }
}
