<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Usage;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('project_bandwidth')]
#[Description(<<<'MARKDOWN'
    Get bandwidth time series for a project

    Values are bytes. Project transfer is the sum of that project's domains. Transfer is every response, robots included, so it exceeds the viewed traffic AWStats reports. Missing AWStats data is an empty object, not an error.

    Calls GET /api/projects/{username}/bandwidth.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class ProjectBandwidthTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/projects/{username}/bandwidth';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function queryParams(): array
    {
        return [
            'start',
            'end',
            'group_by',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('Name of the project. Sent to the API as `username`.')->required(),
            'start' => $schema->string()->description('Example: 2026-09-01.')->required(),
            'end' => $schema->string()->description('Example: 2026-09-30.')->required(),
            'group_by' => $schema->string()->description('One of: day, month.')->required(),
        ];
    }
}
