#!/bin/bash
# Account shell, after the clone and after the recipe's files/ are copied in,
# before detection, before the build and before anything is started.
#
# Three things have to be true before the container is created, and nothing
# later in the deploy can do any of them:
#
#   1. the three secrets, which must outlive the checkout and must be the same
#      values on the next deploy as on this one;
#   2. the env file that carries them, because `env_file:` is read when the
#      container is *created* -- a value written afterwards never reaches
#      getenv() in the container, however correct the file looks;
#   3. the data directories, which have to exist before Docker makes the bind
#      mount or the daemon creates them as root and the container, which runs
#      as this account's uid, cannot write to them.
#
# Nothing here moves a compose file aside. tine ships none at the repository
# root, and the glob that would do it is the trap in engine#166: by the time
# this hook runs the engine has already written this recipe's
# docker-compose.override.yml into the project root, so `mv docker-compose.*`
# would carry off this recipe's own healthcheck and the deploy would still
# report success.
set -e
cd ~/project

say() { echo "[tine] $*"; }

# ------------------------------------------------------------------ store --
#
# Not ~/project: every deploy re-clones over it (engine#173) while the
# account's MySQL database -- and the password hash in tine20_accounts -- stays
# exactly where it was, so a password generated beside the code would be a new
# password on every redeploy, matching nothing. engine#173 also writes
# .env.default into the checkout 0644, readable by every other tenant, which is
# the other reason nothing secret belongs there.
#
# A directory rather than the home itself because account homes are root-owned
# and 0755: an account cannot create a file directly in its own home.
STORE="$HOME/.panelalpha/tine"
mkdir -p "$STORE"
chmod 700 "$HOME/.panelalpha" "$STORE"

ENV_FILE="$STORE/app.env"

# 20 base62 characters from openssl with a digit and an upper-case letter
# appended, so the class mix never depends on luck and tine's password policy
# module (Tinebase_Config::PASSWORD_POLICY_*) is satisfied whatever an operator
# turns on later. The base64 punctuation is dropped for two reasons: a human
# has to be able to retype the admin password into the login form, and this
# value goes through `env_file:`, which is not a shell and has its own opinions
# about `#`, quotes and backslashes in a value.
gen() {
    {
        openssl rand -base64 30 | tr -d '/+=\n' | cut -c1-20
        printf 'a7Z'
    } | tr -d '\n'
}

if [ ! -f "$ENV_FILE" ]; then
    (
        umask 077
        {
            echo "# Generated by the PanelAlpha tine recipe. Do not edit: these values"
            echo "# are in the database and in saved credential caches, and changing one"
            echo "# locks the account out of its own installation."
            echo "#"
            echo "# TINE_ADMIN_PASSWORD is the password of the initial tine administrator"
            echo "# created on the first deploy. The login name is in TINE_ADMIN_LOGIN."
            echo "TINE_ADMIN_LOGIN=admin"
            echo "TINE_ADMIN_PASSWORD=$(gen)"
            echo "# The setup user. tine's Setup_Auth (tine20/Setup/Auth.php:31-46) reads"
            echo "# the setupuser key of config.inc.php and fails every login when that"
            echo "# key is absent -- but 'absent' is exactly the state in which"
            echo "# Setup_Server_Json.php:68 stops checking authorisation at all, so the"
            echo "# key is always written and always has a password nobody was given."
            echo "TINE_SETUP_PASSWORD=$(gen)"
            echo "# credentialCacheSharedKey. Tinebase_Auth_CredentialCache encrypts every"
            echo "# stored credential (IMAP/SMTP account passwords, above all) against it."
            echo "# A new value on a redeploy would leave every saved mail account"
            echo "# undecryptable, so it is generated once and never again."
            echo "TINE_CREDENTIAL_CACHE_KEY=$(gen)$(gen)"
        } > "$ENV_FILE"
    )
    chmod 600 "$ENV_FILE"
    say "generated this account's tine secrets in $ENV_FILE"
else
    say "keeping the tine secrets already in $ENV_FILE"
fi

# -------------------------------------------------------------------- data --
#
# $STORE/data is bind-mounted at /data by the compose override and holds
# everything that has to outlive a redeploy:
#
#   /data/files      filesdir. Every uploaded file, every Filemanager node's
#                    content and every mail attachment: Tinebase_FileSystem
#                    writes blobs under it by hash, and the database rows point
#                    at them. Losing it with the checkout would leave a
#                    Filemanager full of files whose content is gone.
#   /data/tmp        tmpdir. Upload staging and temporary export files.
#   /data/caching    caching.path, the File cache backend.
#   /data/sessions   session.path. Keeping it out of the checkout is also what
#                    stops a redeploy logging everyone out.
#
# tine keeps none of these inside the document root of its own accord -- they
# are plain config values (etc/tine20/config.inc.php.mpl names all four) -- so
# there is nothing to symlink and nothing to mount *over* a served directory.
DATA="$STORE/data"
mkdir -p "$DATA/files" "$DATA/tmp" "$DATA/caching" "$DATA/sessions"
chmod 700 "$DATA" "$DATA/files" "$DATA/tmp" "$DATA/caching" "$DATA/sessions"

say "prepared; data directory is $DATA"
