#!/bin/sh
# Runs inside the container on the install and upgrade stages, before Apache
# binds. Idempotent: the upgrade stage replays it on every redeploy and on
# every container restart.
#
# This file sits in the project root rather than in a panelalpha/ directory
# because the project root *is* the document root here -- and the generated
# vhost denies exactly two shapes of engine file, by name:
#
#     <FilesMatch "^(?:docker-compose\.ya?ml|panelalpha[-.])">
#
# so `panelalpha-setup.sh` is denied while `panelalpha/setup.sh` would be
# served as plain text. (resources/deploy/templates/apache-vhost.stub)
set -e
cd /app

log() { echo "[mediawiki] $*" >&2; }
die() { log "$*"; exit 1; }

DATA=/data
LS="${DATA}/LocalSettings.php"
PA_SETTINGS="${DATA}/PanelAlphaSettings.php"
CREDENTIALS="${DATA}/admin-credentials"

# ---------------------------------------------------------------------------
# 0. What the container was handed.
[ -d "${DATA}" ] || die "${DATA} is not mounted; is the compose override still in overrides/?"
[ -n "${DB_HOST:-}" ] && [ -n "${DB_DATABASE:-}" ] \
    || die "no DB_* in the environment; is 'database: mysql' still in panelalpha.yaml?"

# The php platform resolves vendor/ on the host in the build stage. If it is
# not here the deploy has already gone wrong, and saying so now is better than
# an HTTP 500 from includes/PHPVersionCheck.php:150 -- which is exactly the
# failure this recipe exists to fix, and which looks like a successful deploy.
[ -f /app/vendor/autoload.php ] \
    || die "vendor/autoload.php is missing: composer install did not run or did not finish"

# Upstream writes this from its post-install-cmd Composer hook
# (MediaWiki\Composer\ComposerVendorHtaccessCreator), and the platform runs
# composer with --no-scripts, so the hook never fires. MediaWiki serves from
# its own root, which makes /vendor/... a URL. files/.htaccess denies the path
# from the document root as well; this is upstream's own file, put back where
# upstream would have put it, so the tree is what a hand install produces.
if [ -d /app/vendor ] && [ ! -f /app/vendor/.htaccess ]; then
    printf 'Require all denied\nSatisfy All\n' > /app/vendor/.htaccess
    log "wrote vendor/.htaccess (composer --no-scripts skipped upstream's hook)"
fi

# ---------------------------------------------------------------------------
# 1. The settings that belong to *this* deploy.
#
#    Written every time, and separately from LocalSettings.php, because the
#    two have opposite lifetimes. LocalSettings.php holds $wgSecretKey and
#    $wgUpgradeKey: regenerating those would invalidate every session and
#    every edit token on the wiki, so it is written once by MediaWiki's own
#    installer and never touched again. $wgServer is the account's domain,
#    which the engine may change between deploys, so it has to be rewritten --
#    and a wrong $wgServer is not cosmetic: MediaWiki builds every absolute
#    URL, every redirect and every login cookie domain from it.
#
#    Required from the end of LocalSettings.php, so these win over whatever
#    the installer wrote.
MW_SERVER="${APP_URL:-}"
if [ -z "${MW_SERVER}" ]; then
    # No public URL yet. MediaWiki refuses to boot without $wgServer
    # (includes/Setup.php:376), so a placeholder that is obviously a
    # placeholder beats a fatal.
    MW_SERVER="http://localhost:8000"
    log "APP_URL is empty; \$wgServer falls back to ${MW_SERVER}"
fi
# Strip any trailing slash: MediaWiki concatenates $wgServer with paths that
# already begin with one, and '//index.php' is a protocol-relative URL.
MW_SERVER=$(printf '%s' "${MW_SERVER}" | sed 's:/*$::')

# Whether to force https is a property of the address the account was given,
# not of the recipe. An account on a panelalpha.online name is behind a proxy
# that terminates TLS and the value is right; an account whose deploy fell back
# to a `.local` name that resolves nowhere would be redirected to an https URL
# nothing answers, and Special:UserLogin would refuse to set a cookie at all.
case "${MW_SERVER}" in
    https://*) MW_HTTPS=true ;;
    *)         MW_HTTPS=false ;;
esac

cat > "${PA_SETTINGS}" <<EOF
<?php
# Generated by PanelAlpha on every deploy -- do not edit, your changes will be
# overwritten. Put your own settings in LocalSettings.php above the line that
# requires this file.
#
# Only what depends on this particular deployment is here. Everything with a
# lifetime longer than one deploy -- \$wgSecretKey, \$wgUpgradeKey,
# \$wgDBpassword -- was written once by MediaWiki's own installer and is never
# regenerated.

if ( !defined( 'MEDIAWIKI' ) ) { exit; }

# The account's public address. Rewritten every deploy because the engine may
# hand this account a different domain; MediaWiki builds every absolute URL,
# every redirect and the login cookie's domain from it.
\$wgServer = "${MW_SERVER}";

# TLS is terminated at the proxy in front of this container, so the request
# MediaWiki sees is plain http even when the visitor's was not. Without these
# every internal link would be http:// on an https page, and the login cookie
# would go out without its secure flag. False when the account's own address is
# not https, because forcing a redirect to a scheme nothing answers is worse
# than not forcing one.
\$wgForceHTTPS = ${MW_HTTPS};
\$wgCookieSecure = ${MW_HTTPS};

# The document root is the repository root, so the wiki is at /.
\$wgScriptPath = "";
\$wgArticlePath = "/index.php/\$1";
\$wgUsePathInfo = true;

# Without this, GET / answers 301 to /index.php/Main_Page -- the account's own
# address is a redirect to the wiki rather than the wiki. MediaWiki has said
# since 1.34 that a wiki whose main page *is* the domain root should say so:
# Title::getLocalURL() then returns '/' for the main page
# (includes/Title/Title.php:2230) and nothing has to be normalised away.
\$wgMainPageIsDomainRoot = true;

# Uploads live on the bind mount, which survives a redeploy; the URL stays
# /images/... because hooks/prepare.sh made images/ a symlink to it.
\$wgEnableUploads = true;
\$wgUploadDirectory = "/data/images";
\$wgUploadPath = "\$wgScriptPath/images";

# The localisation cache, off the directory a redeploy deletes. Without this
# MediaWiki stores it in the database, which is slower and grows it.
\$wgCacheDirectory = "/data/cache";

# Errors go to the container's stderr, where \`docker logs\` and the deploy log
# can see them, and never to a browser.
\$wgShowExceptionDetails = false;
\$wgShowDBErrorBacktrace = false;
\$wgDebugLogFile = "";

# The default is 'apache', which resolves to nothing outside a Wikimedia
# cluster; MediaWiki's own recommendation for a single server is to let it use
# the database for object and message caching, which the installer already
# configured.
EOF
chmod 640 "${PA_SETTINGS}"

# ---------------------------------------------------------------------------
# 2. Install, or update.
if [ -f "${LS}" ]; then
    # Every deploy after the first. `update.php` applies whatever schema
    # changes the new code needs and is a no-op when there are none -- which
    # is what stops the first visitor after a version bump from meeting a
    # DBQueryError, and what stops a *pending* schema change from making
    # MediaWiki throw on every request.
    log "LocalSettings.php is there; running maintenance/run.php update"
    php maintenance/run.php update --quick >&2 \
        || die "maintenance/run.php update failed; the wiki may be on a schema the code cannot use"
    log "update finished"
else
    # The first deploy. MediaWiki's own installer, not a reimplementation of
    # it: the same CliInstaller that `maintenance/run.php install` is, with
    # the same environment checks, the same ~50 tables, the same Main Page and
    # the same LocalSettingsGenerator.
    [ -f "${CREDENTIALS}" ] || die "${CREDENTIALS} is missing; hooks/prepare.sh did not run"

    # shellcheck disable=SC1090
    MW_ADMIN_USER=$(sed -n 's/^MEDIAWIKI_ADMIN_USERNAME=//p' "${CREDENTIALS}" | head -n 1)
    [ -n "${MW_ADMIN_USER}" ] || MW_ADMIN_USER=Admin

    # The password goes in through --passfile rather than --pass. An argument
    # is in /proc/<pid>/cmdline, which every process in this container can
    # read, and in the deploy log if the command is ever echoed; a file is
    # 0600 on a mount only this account can reach. Same for --dbpassfile: the
    # engine handed the database password in through the environment, and
    # putting it back on a command line would widen it for no reason.
    PASSFILE=$(mktemp)
    DBPASSFILE=$(mktemp)
    chmod 600 "${PASSFILE}" "${DBPASSFILE}"
    # shellcheck disable=SC2064
    trap "rm -f '${PASSFILE}' '${DBPASSFILE}'" EXIT INT TERM
    sed -n 's/^MEDIAWIKI_ADMIN_PASSWORD=//p' "${CREDENTIALS}" | head -n 1 \
        | tr -d '\n' > "${PASSFILE}"
    printf '%s' "${DB_PASSWORD:-}" > "${DBPASSFILE}"
    [ -s "${PASSFILE}" ] || die "no MEDIAWIKI_ADMIN_PASSWORD in ${CREDENTIALS}"

    # --installdbuser is deliberately not passed. CliInstaller reads its
    # absence as "use the ordinary database user for the install too" and
    # leaves _CreateDBAccount false (includes/Installer/CliInstaller.php:87);
    # passing it would make MediaWiki try to CREATE USER and GRANT, which the
    # account's own MySQL user cannot do and does not need to -- the engine
    # provisioned the database and the user before this container started.
    # MysqlDatabaseCreator only issues CREATE DATABASE when
    # information_schema.schemata says it is missing, and it is not.
    #
    # --scriptpath "" because the wiki is at the root of its own domain.
    # --confpath /data so LocalSettings.php is written on the bind mount and
    # never in the document root; MW_CONFIG_FILE in the compose override is
    # what makes MediaWiki read it back from there.
    log "installing MediaWiki for bureaucrat '${MW_ADMIN_USER}' at ${MW_SERVER}"
    php maintenance/run.php install \
        --dbtype mysql \
        --dbserver "${DB_HOST}" \
        --dbname "${DB_DATABASE}" \
        --dbuser "${DB_USERNAME}" \
        --dbpassfile "${DBPASSFILE}" \
        --server "${MW_SERVER}" \
        --scriptpath "" \
        --lang en \
        --passfile "${PASSFILE}" \
        --confpath "${DATA}" \
        "${MW_SITENAME:-Wiki}" "${MW_ADMIN_USER}" >&2 \
        || die "maintenance/run.php install failed"

    [ -f "${LS}" ] || die "the installer reported success but ${LS} is not there"
    rm -f "${PASSFILE}" "${DBPASSFILE}"
    trap - EXIT INT TERM
    chmod 600 "${LS}"
    log "installed; the bureaucrat's password is in ~/.panelalpha/mediawiki/admin-credentials"
fi

# ---------------------------------------------------------------------------
# 3. Hook the per-deploy settings onto the end of the settings file.
#
#    Appended once, and to the end on purpose: PHP takes the last assignment,
#    so anything the operator adds to LocalSettings.php *above* this line is
#    overridden by the generated file, and anything below it wins. That is the
#    right way round -- $wgServer has to track the account's domain, and an
#    operator who really wants to pin it can say so after the require.
if ! grep -q 'PanelAlphaSettings.php' "${LS}"; then
    cat >> "${LS}" <<'EOF'

# ---------------------------------------------------------------------------
# Added by PanelAlpha. The settings that depend on how this account is hosted
# -- $wgServer above all -- are regenerated on every deploy and live in their
# own file, so that this one, which holds $wgSecretKey and $wgUpgradeKey, is
# never rewritten. Your own settings go above this line.
if ( file_exists( '/data/PanelAlphaSettings.php' ) ) {
	require_once '/data/PanelAlphaSettings.php';
}
EOF
    log "LocalSettings.php now requires PanelAlphaSettings.php"
fi

# ---------------------------------------------------------------------------
# 4. What the wiki is allowed to write.
#
#    The container runs as the account's own uid (the generated compose file
#    says `user: "<uid>:<gid>"`), so these are the account's directories; this
#    is about them existing, not about ownership. MediaWiki creates the
#    two-level hash directories under images/ itself on the first upload, and
#    the localisation cache directory on the first request.
mkdir -p /data/images /data/cache
chmod 755 /data/images /data/cache

log "setup finished"
