<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\SFTPAccounts;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('sftp_account_create')]
#[Description(<<<'MARKDOWN'
    Create an SFTP account
    MARKDOWN)]
#[IsDestructive]
class SftpAccountCreateTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/sftp-accounts';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'sftp_username',
            'auth_method',
            'password',
            'public_key',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'sftp_username' => $schema->string()->description('Name of the SFTP account. Must start with "<project username>_". Also accepted as `username`; documented under this name because `username` is already this route\'s path parameter. Example: johndoe_backup.')->required(),
            'auth_method' => $schema->string()->description('Comma-separated list of "password" and/or "public_key". Each method listed requires its credential below. Example: password.')->required(),
            'password' => $schema->string()->description('Required when auth_method includes "password". Minimum 8 characters.'),
            'public_key' => $schema->string()->description('Required when auth_method includes "public_key".'),
        ];
    }
}
