<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\FTPAccounts;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('ftp_account_create')]
#[Description(<<<'MARKDOWN'
    Create an FTP account
    MARKDOWN)]
#[IsDestructive]
class FtpAccountCreateTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/ftp-accounts';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'user',
            'domain',
            'password',
            'directory',
            'unlimited_quota',
            'quota',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'user' => $schema->string()->description('Example: ftpuser1.')->required(),
            'domain' => $schema->string()->description('Example: example.com.')->required(),
            'password' => $schema->string()->required(),
            'directory' => $schema->string()->description('Example: /public_html.'),
            'unlimited_quota' => $schema->boolean(),
            'quota' => $schema->integer()->description('Quota in MB'),
        ];
    }
}
