#!/bin/bash
set -e
cd ~/project

# The generated password lives in $HOME, not in ~/project, and that is not a
# style choice. ProjectTree::clearContents() runs `find ~/project -mindepth 1
# -maxdepth 1 -exec rm -rf` before every clone, dotfiles included, so a .env
# written here is gone by the next deploy — while the inner Docker volumes that
# hold Tracim's SQLite database are not. A password regenerated on redeploy
# would be one the database never learns and nobody was ever told.
STORE="${HOME}/.panelalpha/tracim.env"

if [ ! -f "${STORE}" ]; then
    mkdir -p "$(dirname "${STORE}")"
    chmod 700 "$(dirname "${STORE}")"
    umask 077
    cat > "${STORE}" <<EOF
# Generated by the PanelAlpha Tracim recipe. Kept out of ~/project, which is
# emptied and re-cloned on every deploy.
#
# Tracim's first boot always creates the same administrator:
# InitializeDBCommand._populate_database() calls create_user(name="Global
# manager", username="TheAdmin", email="admin@admin.admin",
# password="admin@admin.admin"). Not a placeholder, not printed for the
# operator to change — every Tracim starts with it.
# files/panelalpha-setup.sh replaces that password with this one as soon as the
# API answers.
#
# The login stays admin@admin.admin: changing the address is a second API call
# that can fail on its own, and the password is the secret, not the address.
TRACIM_ADMIN_LOGIN=admin@admin.admin
TRACIM_SHIPPED_PASSWORD=admin@admin.admin
# Alphanumeric: this value is interpolated by compose, embedded in a JSON body
# by the setup script and typed by a human. Tracim's own rule is 6 to 512
# characters with no character-class requirement (User.MIN_PASSWORD_LENGTH).
TRACIM_ADMIN_PASSWORD=$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | cut -c1-24)
EOF
    chmod 600 "${STORE}"
fi

# The image tag is a constant, which is unusual for these recipes and is the
# registry's fault rather than a shortcut. Upstream's README says it outright:
# "Docker images for the latest Tracim versions are only available to our
# paying customers". Docker Hub agrees — algoo/tracim's newest public release
# tag is 2025-04.00 and `latest` points at it, while this checkout's
# CHANGELOG.md is already on 2026.10.00. There is no public tag matching the
# tree, so deriving one from the checkout the way the Ghost and Mattermost
# recipes do would only produce a 404 at `up -d`. `unstable` is rebuilt from
# develop and would match, but it is named what it is.
#
# Rewritten every deploy, unlike the secrets above, so changing this line in
# the recipe actually moves a redeployed account.
cat > .env <<EOF
TRACIM_IMAGE=algoo/tracim:latest
EOF
cat "${STORE}" >> .env
chmod 600 .env

# .env is what compose interpolates; this is the file a human is pointed at.
ADMIN_LOGIN=$(sed -n 's/^TRACIM_ADMIN_LOGIN=//p' "${STORE}" | head -1)
ADMIN_PASSWORD=$(sed -n 's/^TRACIM_ADMIN_PASSWORD=//p' "${STORE}" | head -1)
cat > .panelalpha-admin-password <<EOF
# Written by PanelAlpha on the first deploy. Tracim seeds a fixed
# administrator on every first boot — admin@admin.admin with the password
# admin@admin.admin, hard-coded in tracim_backend/command/database.py — so
# PanelAlpha changes it to this one before the site is useful to anybody.
TRACIM_ADMIN_LOGIN=${ADMIN_LOGIN}
TRACIM_ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF
chmod 600 .panelalpha-admin-password
