<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\MySQLDatabases;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;

#[Name('mysql_database_delete')]
#[Description(<<<'MARKDOWN'
    Delete a MySQL database
    MARKDOWN)]
#[IsDestructive]
#[IsIdempotent]
class MysqlDatabaseDeleteTool extends ApiTool
{
    protected function method(): string
    {
        return 'DELETE';
    }

    protected function path(): string
    {
        return '/projects/{username}/mysql/databases/{dbname}';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
            'dbname',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'dbname' => $schema->string()->required(),
        ];
    }
}
