#!/bin/bash
set -e
cd ~/project

# 1. The repository's compose.yml is a workstation stack, and the engine reads
#    it for backing services even though it never runs it. RuntimeSidecars
#    kept `database` (mariadb:10), `web` (nginx:alpine), `node` (node:16.13.0)
#    and `padm` (phpmyadmin) alongside the app the php strategy builds: a
#    second webserver, a phpMyAdmin nobody asked for, an unused MariaDB, and a
#    `node` running `encore dev --watch` against a directory it does not have,
#    which restart-looped and made AppHealth report the *application* as
#    restarting. Renaming the file is the whole fix.
#
#    The name matters. RuntimeSidecars looks at COMPOSE_FILE_CANDIDATES, at
#    `<name>.panelalpha-local` stashes, and at a glob of `compose.*.yml` /
#    `docker-compose.*.yml` treated as stack templates -- so `compose.dev.yml`
#    would have been read again, as a template, and brought the MariaDB back.
#    `compose.yml.upstream-dev` matches none of them and is still obviously
#    upstream's file if an operator goes looking.
if [ -f compose.yml ] && [ ! -f compose.yml.upstream-dev ]; then
    mv compose.yml compose.yml.upstream-dev
    echo "[bolt] moved the repository's development compose.yml aside"
fi

# 2. Bolt's extension wiring is generated, and this repository has the
#    generated files for its *dev* extensions committed:
#
#      config/routes/extension_reference-extension.yaml
#          resource: '../../vendor/acmecorp/reference-extension/src/Controller/'
#      config/services_bolt.yaml
#          four `resource: '../vendor/…'` entries
#
#    acmecorp/reference-extension, bolt/configuration-notices-widget,
#    bolt/newswidget and bolt/weatherwidget are all require-dev, and the php
#    manifest installs with `--no-dev`, so none of those directories exist.
#    Kernel::configureContainer() wraps the services_bolt.yaml load in a
#    try/catch for exactly this reason; configureRoutes() does not, so the
#    router throws FileLocatorFileNotFoundException while building its cache
#    and every single request -- frontend, /bolt, anything -- answers 500.
#    That is the `serving-error_page` verdict this recipe exists to fix.
#
#    Both files are regenerated from the installed extensions by
#    `bin/console extensions:configure`, which the install/upgrade stage runs
#    once vendor/ exists. Removing them here is removing build output, not
#    source: the deploy puts back whatever is actually installed.
rm -f config/routes/extension_*.yaml config/routes/extension_*.yml
if [ -f config/services_bolt.yaml ]; then
    printf '# Regenerated by bin/console extensions:configure after the build.\nservices:\n' \
        > config/services_bolt.yaml
fi

# 3. Bolt's four dev-time extension packages, out of require-dev.
#
#    Not tidiness. `Bolt\Extension\ExtensionRegistry::addComposerPackages()`
#    asks `ComposerPackages\Types::get('bolt-extension')` for every extension
#    in the project and throws outright when one of them cannot be loaded:
#
#      The extension "acmecorp/reference-extension" has its 'extra/entrypoint'
#      set to "AcmeCorp\ReferenceExtension\Extension", but that class does not
#      exist
#
#    The registry runs inside Kernel::build()'s compiler pass, so that is a
#    container that never compiles and a 500 on every request, `bin/console`
#    included. It happens because ComposerPackages is generated from
#    composer.lock -- which lists `packages-dev` whether or not they were
#    installed -- while the php manifest installs with `--no-dev`. acmecorp's
#    is a demo extension and the other three are dashboard widgets (news,
#    weather, configuration notices); none of them belongs on a hosted site.
#
#    Removed from composer.json rather than worked around after the fact,
#    because the lock is written by the deploy: bolt/core commits none, so the
#    engine's `composer install` resolves from scratch and whatever is in
#    require-dev at that moment is what ends up in the generated lock.
#
#    Scoped to the require-dev block: the same four names appear under
#    `conflict` as lower-bound pins, and deleting those leaves a trailing comma
#    and invalid JSON. Written back only if awk produced something.
awk '
  /^[[:space:]]*"require-dev"[[:space:]]*:[[:space:]]*\{/ { indev = 1; print; next }
  indev && /^[[:space:]]*\}/                             { indev = 0; print; next }
  indev && /"(acmecorp\/reference-extension|bolt\/configuration-notices-widget|bolt\/newswidget|bolt\/weatherwidget)"[[:space:]]*:/ { next }
  { print }
' composer.json > composer.json.panelalpha
if [ -s composer.json.panelalpha ]; then
    mv composer.json.panelalpha composer.json
else
    rm -f composer.json.panelalpha
    echo "[bolt] could not rewrite composer.json; leaving it alone" >&2
fi

# 4. Secrets, in .env itself.
#
#    `.env.local` is the file Symfony documents for this and the file .env's own
#    header points at -- and it does not work here. The generated compose file
#    carries `env_file: - .env`, so every line of the repository's .env becomes
#    a real process environment variable, and Dotenv::populate() never
#    overwrites one of those. An APP_SECRET in .env.local is read, found to be
#    shadowed, and discarded. Measured on a deploy that had one:
#    `printenv APP_SECRET` in the container printed `!ChangeMe!`.
#
#    So the placeholder is replaced in place. Only the exact published value is
#    matched, which makes this idempotent and leaves an operator's own secret
#    alone. `git pull` sees a modified .env; that is the cost of the env_file,
#    and the alternative is a production site signing its CSRF tokens and
#    remember-me cookies with a string printed in a public repository.
#
#    DATABASE_URL is not touched: .env already points at
#    sqlite:///%kernel.project_dir%/var/data/bolt.sqlite, which is right.
#    MAILER_DSN is, because smtp://localhost in a container with no MTA turns
#    Bolt's password-reset form into a 500 rather than a no-op.
if grep -q '^APP_SECRET=!ChangeMe!$' .env; then
    sed -i "s|^APP_SECRET=!ChangeMe!\$|APP_SECRET=$(openssl rand -hex 32)|" .env
fi
if grep -q '^MAILER_DSN=smtp://localhost$' .env; then
    sed -i 's|^MAILER_DSN=smtp://localhost$|MAILER_DSN=null://null|' .env
fi

# 5. The first administrator's password, generated per account and never a
#    default. Written here rather than in the container so it exists before
#    anything could serve a page, and read back by panelalpha/bolt-setup.sh
#    when it creates the user. openssl rather than $RANDOM: this is the only
#    credential the account has.
#
#    The umask is inside a subshell on purpose: it has to cover the redirection
#    that creates the file, so the password is never briefly world-readable,
#    and it must not survive into the rest of this script. A leaked `umask 077`
#    here made var/cache mode 700, which the engine (www-data) cannot scan, and
#    the deploy died on `scandir(.../var/cache): Permission denied`.
if [ ! -f .panelalpha-admin-password ]; then
    ( umask 077; openssl rand -base64 18 | tr -d '/+=' > .panelalpha-admin-password )
    chmod 600 .panelalpha-admin-password
fi

# 6. Doctrine writes the SQLite file into var/data and Symfony its cache and
#    logs into var/. Only var/log and var/data/.gitkeep are in the checkout.
#    Readable by the engine as well as the account: it walks the tree looking
#    for the document root and stops the deploy on a directory it cannot open.
mkdir -p var/data var/cache var/log
chmod 755 var var/data var/cache var/log
