#!/bin/bash
set -e
cd ~/project

# Three secrets and an image tag, for a compose file that cannot generate any
# of them, written where `docker compose` reads variables from: the project's
# .env.
#
# Koillection's repository *ships* a root .env -- Symfony's committed defaults,
# including DB_PASSWORD=koillection and an empty APP_SECRET. Compose reads that
# same file for interpolation, so a bare `if [ ! -f .env ]` guard (Ghost's)
# would never fire here, and doing nothing would hand the stack the published
# password out of the repository. The values below are therefore removed and
# re-added rather than appended blindly.
#
# The secrets themselves live outside the checkout, in $HOME, because
# ~/project does not survive a deploy: GitRepository::cloneConfiguredRepository
# calls clearContents() on it before every clone, while the postgres volume and
# the uploads volume persist. A password regenerated on redeploy would be a
# password the database no longer accepts -- the app would come back up unable
# to log in to its own data. Generated once, reused forever after.
STORE="${HOME}/.panelalpha/koillection.env"

if [ ! -f "${STORE}" ]; then
    mkdir -p "$(dirname "${STORE}")"
    chmod 700 "$(dirname "${STORE}")"
    umask 077
    cat > "${STORE}" <<EOF
# Generated by the PanelAlpha Koillection recipe. Kept out of ~/project, which
# is emptied and re-cloned on every deploy.
DB_PASSWORD=$(openssl rand -hex 16)
# docker/entrypoint.sh writes .env.local on every boot with
# \${APP_SECRET:-\$(openssl rand -base64 21)}; unset, it rotates each restart
# and takes every session and remember-me cookie with it (security.yaml signs
# remember_me with APP_SECRET).
APP_SECRET=$(openssl rand -hex 24)
# Same defaulting, but \`lexik:jwt:generate-keypair --skip-if-exists\` keeps the
# keypair it already wrote -- so a rotated passphrase stops opening the private
# key and /api/authentication_token breaks after the first restart.
JWT_PASSPHRASE=$(openssl rand -hex 16)
EOF
    chmod 600 "${STORE}"
fi

# The image tag comes from the checkout rather than a constant here: a clone of
# the 1.8 branch should get a 1.8 image. composer.json's "version" is what
# .github/workflows/docker-release.yml tags the release with
# (docker.io/koillection/koillection:1.8.4). Anything that is not an X.Y.Z
# falls back to :latest -- a development branch's version string is not a
# published tag, and a pull that 404s is a deploy that fails at `up -d`.
VERSION=$(sed -n 's/^[[:space:]]*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' composer.json | head -1)
case "${VERSION}" in
    [0-9]*.[0-9]*.[0-9]*) TAG="${VERSION}" ;;
    *) TAG=latest ;;
esac

# Drop any earlier definition of these four, then append ours, so the value
# compose interpolates is the one this hook wrote and not the repository's.
sed -i -E '/^[[:space:]]*(APP_SECRET|JWT_PASSPHRASE|DB_PASSWORD|KOILLECTION_IMAGE)=/d' .env
{
    echo ""
    echo "# --- PanelAlpha ---"
    echo "KOILLECTION_IMAGE=koillection/koillection:${TAG}"
    cat "${STORE}"
} >> .env
chmod 600 .env
