#!/bin/sh
# tine's configuration and installation, driven from the deploy instead of from
# a visitor.
#
# Runs inside the application container on the install and upgrade stages,
# which is *before* Apache binds: the generated entrypoint runs the stage
# commands and only then execs panelalpha-serve. That ordering is the whole
# security argument of this recipe -- see the header of files/tine20/.htaccess
# and README.md -- because until config.inc.php exists, tine's setup JSON API
# is completely unauthenticated (Setup/Server/Json.php:68).
#
# Idempotent: the upgrade stage replays it on every redeploy, and a redeploy
# has re-cloned over ~/project, so config.inc.php is written every time rather
# than only when missing. There is never a file here to preserve and the
# values the container was handed are by definition the ones that work.
#
# This file lives in the document root -- tine serves from tine20/ and
# `app_root: tine20` makes that /app -- and is not reachable over HTTP twice
# over: the generated vhost denies any basename starting `panelalpha-`
# (resources/deploy/templates/apache-vhost.stub), and .htaccess rewrites every
# .php request but index.php into index.php.
set -e

cd /app

log() { echo "[tine] $*" >&2; }
die() { echo "[tine] $*" >&2; exit 1; }

# `database: mysql` in panelalpha.yaml is what puts these here, on the
# account's own MySQL server. Without them the config below would be written
# with empty strings and tine would fail much later, on a connection error
# inside the installer, with nothing pointing back at the manifest.
[ -n "${DB_HOST:-}" ] || die "no DB_HOST in the environment; is 'database: mysql' still in panelalpha.yaml?"
[ -n "${DB_DATABASE:-}" ] || die "no DB_DATABASE in the environment; is 'database: mysql' still in panelalpha.yaml?"

# The three secrets hooks/prepare.sh generated, delivered by the second
# `env_file:` in the compose override. env_file is read at container creation,
# so if this is empty the file did not exist when the container was made and a
# restart -- not another write -- is what fixes it.
[ -n "${TINE_SETUP_PASSWORD:-}" ] || die "no TINE_SETUP_PASSWORD; ~/.panelalpha/tine/app.env is missing or was written after the container was created"
[ -n "${TINE_ADMIN_PASSWORD:-}" ] || die "no TINE_ADMIN_PASSWORD; see ~/.panelalpha/tine/app.env"
[ -n "${TINE_CREDENTIAL_CACHE_KEY:-}" ] || die "no TINE_CREDENTIAL_CACHE_KEY; see ~/.panelalpha/tine/app.env"

# The bind mount from the compose override. Every upload, every Filemanager
# node's content and every mail attachment goes under /data/files, which is the
# only reason a redeploy is safe here -- so a missing mount is a deploy that
# would quietly start writing files into a directory the next clone deletes.
[ -d /data ] || die "/data is not mounted; check overrides/docker-compose.override.yml"
mkdir -p /data/files /data/tmp /data/caching /data/sessions

# The client bundles. Without them Tinebase_Core::detectBuildType() answers
# DEVELOPMENT and getAssetsMap() goes looking for a webpack-dev-server, so the
# application would install cleanly and then throw on every page. Checked here
# as well as in panelalpha-build.sh because this is the last point before
# Apache binds.
[ -f /app/Tinebase/js/webpack-assets-FAT.json ] \
    || die "Tinebase/js/webpack-assets-FAT.json is missing; the frontend build did not run or did not finish"

# --------------------------------------------------------------- config ----
#
# config.inc.php is found through get_include_path() (Setup_Core::
# getConfigFilePath(), tine20/Setup/Core.php:152-164), and composer's
# include_paths.php puts /app first because tine20/composer.json declares
# `"include-path": ["", ...]`. So this path, and no other, is the config file.
#
# It holds getenv() calls rather than values, so the file itself is not a
# secret: the database password and the three generated secrets stay in the
# container's environment and never touch the disk inside ~/project. That
# matters here more than usual, because the document root *is* ~/project/tine20
# and this file sits in it.
log "writing config.inc.php"
cat > /app/config.inc.php <<'PHP'
<?php
/*
 * Generated by the PanelAlpha tine recipe on every deploy. Do not edit: a
 * redeploy re-clones ~/project and writes this file again.
 *
 * Every secret is a getenv() call. DB_* come from the database the engine
 * provisioned on the account's own MySQL server (`database: mysql`);
 * TINE_* come from ~/.panelalpha/tine/app.env, which hooks/prepare.sh
 * generated once and the compose override delivers as a second env_file.
 */
return [
    // AUTODETECT rather than a literal: Tinebase_Core::detectBuildType()
    // answers RELEASE exactly when Tinebase/js/webpack-assets-FAT.json is
    // there, which is the same condition panelalpha-setup.sh refuses to boot
    // without. Writing 'RELEASE' here would instead promise bundles that might
    // not exist.
    'buildtype' => 'AUTODETECT',

    'database' => [
        'host'        => getenv('DB_HOST') ?: 'localhost',
        'port'        => (int) (getenv('DB_PORT') ?: 3306),
        'dbname'      => getenv('DB_DATABASE'),
        'username'    => getenv('DB_USERNAME'),
        'password'    => getenv('DB_PASSWORD'),
        'adapter'     => 'pdo_mysql',
        'tableprefix' => 'tine20_',
    ],

    // Not optional, and not only a convenience. Setup_Server_Json.php:68 makes
    // the *entire* setup JSON API anonymous while no config file exists, and
    // Setup_Auth (Setup/Auth.php:31-46) refuses every login while this key is
    // absent -- so "no setupuser" is not a locked door, it is no door. The
    // password is generated per account and handed to nobody; the HTTP route
    // to setup.php is denied in .htaccess as well.
    'setupuser' => [
        'username' => 'setupuser',
        'password' => getenv('TINE_SETUP_PASSWORD'),
    ],

    // The public origin, from the compose file the engine generated. Declaring
    // it short-circuits Tinebase_Core::getUrl()'s request-derived branch
    // (Tinebase/Core.php), which would read the scheme from the connection --
    // and the connection to this container is plain HTTP behind a proxy that
    // terminated TLS, so every absolute URL tine generated (SSO redirects,
    // CalDAV/CardDAV discovery, notification mail links) would say http://.
    'tine20URL' => getenv('APP_URL') ?: null,

    // All four are outside the checkout, on the bind mount, because a deploy
    // clears and re-clones ~/project (engine#173). tine reads them as plain
    // config values, so there is nothing to symlink.
    'filesdir' => '/data/files',
    'tmpdir'   => '/data/tmp',
    'caching'  => [
        'active'   => true,
        'backend'  => 'File',
        'path'     => '/data/caching',
        'lifetime' => 3600,
    ],
    'session'  => [
        'lifetime' => 86400,
        'backend'  => 'File',
        'path'     => '/data/sessions',
    ],

    // Tinebase_Auth_CredentialCache encrypts every stored credential against
    // this -- an IMAP account's password above all. Generated once per account
    // and kept out of the checkout for exactly that reason.
    'credentialCacheSharedKey' => getenv('TINE_CREDENTIAL_CACHE_KEY'),

    // Off. tine's action queue is Redis-only (Tinebase_ActionQueue) and this
    // platform gives a PHP project one container and no Redis; with it off,
    // tine runs the same work synchronously in the request.
    'actionqueue' => ['active' => false],

    // The container's stderr, which is what `docker logs` and the panel's log
    // viewer read. NOTICE (5) rather than tine's own DEBUG default: at DEBUG
    // this application writes several megabytes per page load.
    'logger' => [
        'active'   => true,
        'filename' => 'php://stderr',
        'priority' => 5,
    ],

    'maintenanceMode' => false,
];
PHP
chmod 600 /app/config.inc.php

# ---------------------------------------------- client translations ----
#
# The other half of the client build, and it cannot happen in the Node
# container because it is PHP. Once webpack-assets-FAT.json exists the
# installation is RELEASE, and in RELEASE tine serves *prebuilt*
# `<App>/js/<App>-lang-<locale>.js` files instead of generating translations
# per request -- files a checkout does not have. Without them the client waits
# ten seconds for Tine.__translationData.__isLoaded, puts up "A problem with
# the translations was detected" and reloads into the same wait, for ever,
# while the health probe sees a perfectly good HTTP 200. Measured, on the first
# green deploy of this recipe. panelalpha-langbuild.php has the detail.
php /app/panelalpha-langbuild.php

# --------------------------------------------------- install or update ----
#
# `--is_installed` exits 0 when Tinebase is installed and 1 otherwise
# (Setup/Frontend/Cli.php::_isInstalled), and it speaks to the database
# directly, so it is a safe question to ask before tine exists.
if php setup.php --is_installed >/dev/null 2>&1; then
    # `--update_needed` is inverted on purpose upstream: it exits 1 -- and
    # prints "Update required" -- when there is work to do.
    if php setup.php --update_needed >/dev/null 2>&1; then
        log "already installed and the schema matches the checkout"
    else
        log "the checkout is newer than the schema; running tine's own update"
        php setup.php --update
    fi
else
    log "installing tine (this creates the schema for every bundled application)"
    # acceptedTermsVersion, adminLoginName and adminPassword are passed as
    # arguments because the alternative is Setup_Frontend_Cli::
    # _promptRemainingOptions(), which writes the whole of tine20/LICENSE and
    # the privacy notice to stdout and then blocks on fgets(STDIN). See
    # README.md on what accepting the terms here means.
    #
    # `--install` with no value installs every application that is not marked
    # installOnDemand (Setup_Controller::getInstallableApplications()), which
    # is 29 of the 31 in the tree; ExampleApplication and SaasInstance are the
    # two it skips, and both are marked that way upstream.
    php setup.php --install -- \
        acceptedTermsVersion=1 \
        adminLoginName="${TINE_ADMIN_LOGIN:-admin}" \
        adminPassword="$TINE_ADMIN_PASSWORD"

    php setup.php --is_installed >/dev/null 2>&1 \
        || die "the installer reported success but Tinebase is not installed"
    log "installed; the administrator password is in ~/.panelalpha/tine/app.env"
fi

# The cache is on the bind mount and outlives the checkout, so after a version
# bump it would hold the previous release's class map, config and translations
# against this release's code. Cheap to drop and it is rebuilt on first use.
log "clearing caches"
php setup.php --clear_cache >/dev/null 2>&1 || log "clear_cache failed (not fatal)"

log "ready"
