<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\CronJobs;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;

#[Name('cron_job_update')]
#[Description(<<<'MARKDOWN'
    Update a cron job

    PHP hosting projects only: a dind account does not run the project crontab, and a dind project answers 422.
    MARKDOWN)]
#[IsDestructive]
#[IsIdempotent]
class CronJobUpdateTool extends ApiTool
{
    protected function method(): string
    {
        return 'PUT';
    }

    protected function path(): string
    {
        return '/projects/{username}/cron-jobs/{hash}';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
            'hash',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'command',
            'minute',
            'hour',
            'day_of_month',
            'month',
            'day_of_week',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'hash' => $schema->string()->required(),
            'command' => $schema->string()->required(),
            'minute' => $schema->string()->required(),
            'hour' => $schema->string()->required(),
            'day_of_month' => $schema->string()->required(),
            'month' => $schema->string()->required(),
            'day_of_week' => $schema->string()->required(),
        ];
    }
}
