<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Containers;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('app_health_check')]
#[Description(<<<'MARKDOWN'
    Check that the deployed application answers on its published ports

    Probes the app on its published ports from inside its container, bypassing domain, DNS, TLS and proxy. `healthy`: something answered (null: no port published). `serving`: whether it is the app - `ok`, or what answered instead; `checks` say why and what to do.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class AppHealthCheckTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/projects/{username}/app/health';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function queryParams(): array
    {
        return [
            'timeout',
            'attempts',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'timeout' => $schema->integer(),
            'attempts' => $schema->integer(),
        ];
    }
}
