<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\SSLCertificates;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;

#[Name('ssl_cert_install')]
#[Description(<<<'MARKDOWN'
    Install a custom SSL certificate on a domain
    MARKDOWN)]
#[IsDestructive]
#[IsIdempotent]
class SslCertInstallTool extends ApiTool
{
    protected function method(): string
    {
        return 'PUT';
    }

    protected function path(): string
    {
        return '/projects/{username}/domains/{domain}/install-ssl-cert';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
            'domain',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'cert',
            'key',
            'ca',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'domain' => $schema->string()->required(),
            'cert' => $schema->string()->description('PEM-encoded certificate')->required(),
            'key' => $schema->string()->description('PEM-encoded private key')->required(),
            'ca' => $schema->string()->description('PEM-encoded CA bundle'),
        ];
    }
}
