<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Tasks;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('task_log_list')]
#[Description(<<<'MARKDOWN'
    Page of task log lines after a timestamp and/or id cursor

    Pass `since` as unix seconds or an ISO datetime to keep only rows with created_at greater than that instant. Pass `after_id` to skip rows at or below that id (needed when many lines share the same second). Both filters AND together. Prefer this over the logs embedded in GET /tasks/{id} when polling by time.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class TaskLogListTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/tasks/{id}/logs';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'id',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function queryParams(): array
    {
        return [
            'since',
            'after_id',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'id' => $schema->integer()->required(),
            'since' => $schema->string(),
            'after_id' => $schema->integer(),
        ];
    }
}
