<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Tasks;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('task_log_stream')]
#[Description(<<<'MARKDOWN'
    Stream task log lines as NDJSON until the task finishes

    Chunked NDJSON without Content-Length. Each log line is one JSON object; a final `{"type":"finish","status":"..."}` frame closes the stream when the task is terminal and no further lines remain. Optional `since` / `after_id` skip the backlog. Long-lived: MCP clients should poll GET /tasks/{id}/logs instead.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class TaskLogStreamTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/tasks/{id}/logs/stream';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'id',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function queryParams(): array
    {
        return [
            'since',
            'after_id',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'id' => $schema->integer()->required(),
            'since' => $schema->string(),
            'after_id' => $schema->integer(),
        ];
    }
}
