#!/bin/bash
# Runs on the account after the clone, before the build.
#
# Geeftlist's compose stack needs four secrets and a set of persistent paths
# that a checkout cannot carry: ~/project is emptied and re-cloned on every
# deploy (engine#173), so anything that must survive one lives in
# ~/.panelalpha/geeftlist instead. The secrets are generated once and reused
# forever after -- a rotated DB password would lock the app out of a database
# that survived the redeploy, and a rotated GEEFTER_SESSION_SECRET_KEY would
# log every user out on each deploy.
set -e
cd ~/project

STATE="${HOME}/.panelalpha/geeftlist"
STORE="${STATE}/geeftlist.env"

say() { echo "[panelalpha] geeftlist: $*"; }

# Only secrets live here. Uploaded gift images go in a named volume instead
# (the image writes them as uid 33, not the account uid, so a bind mount here
# could not be made writable without taking the dir out of the account's own
# ownership) -- see overrides/docker-compose.yml.
mkdir -p "${STATE}"
chmod 700 "${HOME}/.panelalpha" "${STATE}"

# Generated once. Written outside ~/project because that tree does not survive
# a deploy, while the DB named volume and the userdata bind mount do.
if [ ! -f "${STORE}" ]; then
    umask 077
    cat > "${STORE}" <<EOF
# Generated by the PanelAlpha Geeftlist recipe on the first deploy. Kept out of
# ~/project, which is emptied and re-cloned every deploy.
MARIADB_PASSWORD=$(openssl rand -hex 24)
MARIADB_ROOT_PASSWORD=$(openssl rand -hex 24)
# Must be 48+ characters (app checks). Secures JWT API tokens.
AUTHENTICATION_JWT_SECRET_KEY=$(openssl rand -hex 32)
# Secures session IDs. Changing it terminates every active session, so it is
# generated once and never rotated.
GEEFTER_SESSION_SECRET_KEY=$(openssl rand -hex 32)
EOF
    chmod 600 "${STORE}"
    say "generated secrets in ${STORE}"
fi
chmod 600 "${STORE}"

# Compose reads ${VAR} interpolation from ~/project/.env. Written here so the
# engine's ProjectEnvironment keeps this file instead of copying .env.sample,
# and rewritten every deploy from the persisted store above so the values are
# always the same ones. 0644 is the mode the engine writes its own .env with;
# nothing secret is unique to it (the store is the source of truth).
{
    echo "# Written by PanelAlpha. Secrets live in ~/.panelalpha/geeftlist/geeftlist.env"
    echo "GEEFTLIST_IMAGE=nanawel/geeftlist:latest"
    cat "${STORE}"
} > .env
chmod 644 .env

say "prepared; DB and gift images in named volumes, secrets in ${STATE}"
