#!/bin/bash
# Account shell, after the clone and before the host build. Runs on every deploy.
#
# Four jobs, none of which can be done from inside the container and none of
# which can be left to the checkout:
#
#   1. create the persistent store and the two bind-mount sources, *before*
#      compose does -- a missing bind-mount source becomes a root-owned
#      directory the account uid cannot write
#   2. generate the hash salt and the administrator credentials, outside
#      ~/project so they survive the next clone
#   3. create the mount point web/sites/default/files inside the checkout, so
#      Docker does not create it as root
#   4. move an upstream compose file out of the way if one ever appears, by
#      name and never by a glob
#
# Nothing here touches the database or Drupal itself: at this point the
# checkout is four files and there is no vendor/, no web/ and no PHP runtime
# on this side of the container boundary. The install lives in
# files/panelalpha-drupal.php, which runs inside the container.
set -e
cd ~/project

# Account homes are root-owned 755, so the store has to be created rather than
# written into $HOME directly. It is also the only thing that survives a
# deploy: GitRepository::cloneConfiguredRepository empties ~/project before
# every clone (engine #173).
STORE="${HOME}/.panelalpha"
DATA="${STORE}/drupal"
mkdir -p "${STORE}"
chmod 700 "${STORE}"

# ---------------------------------------------------------------------------
# 1. The persistent store.
#
#   app.env            the hash salt and the administrator credentials
#   files/             the public file system: every uploaded image and
#                      document, plus the aggregated CSS/JS and the Twig cache
#   private/           private files, and the config sync directory under it
#
# files/ and private/ are bind-mount sources. Created here and not by Docker,
# and that is the point of doing it in the hook: compose creates a missing
# bind-mount source itself, owned by root and mode 755, and this container runs
# as the account uid -- which could then not write a single uploaded file.
#
# Bind mounts rather than named volumes so the owner can see, copy and restore
# their own uploads over sftp. 755 on files/, not 700: it is the *public* file
# system and Apache serves it directly.
mkdir -p "${DATA}/files" "${DATA}/private/config/sync" "${DATA}/private/tmp"
chmod 700 "${DATA}"
chmod 755 "${DATA}/files"
chmod 700 "${DATA}/private"

# ---------------------------------------------------------------------------
# 2. The secrets, generated once per account.
#
# They reach the container through a second `env_file:` entry at a path that
# climbs out of the checkout, rather than through .env: ProjectEnvironment
# copies .env to .env.default at mode 644 (engine #173). The administrator login
# is the engine's (`credentials:` in panelalpha.yaml), delivered the same way
# from ~/.panelalpha/app-credentials.env.
#
# env_file is read at container *creation*, so this must be complete before
# compose runs -- which it is, the prepare hook is the last thing before the
# build and the build is before `docker compose up`.
APP_ENV="${DATA}/app.env"

if [ ! -f "${APP_ENV}" ]; then
  (
    # In a subshell so the umask covers the redirection that creates the file
    # and does not leak into the rest of this script, where a 077 default would
    # leave a checkout the engine cannot walk.
    umask 077

    # Drupal's own installer mints a 74-character base64 salt. It keys every
    # session cookie, every one-time login link and every form token, so a
    # redeploy that rotated it would sign every logged-in user out and
    # invalidate every password-reset mail in flight. This is the one value
    # that has to be remembered; the database password does not, because
    # AppDatabase::password() already stores it in the account's details and
    # hands the same one back on every deploy.
    HASH_SALT=$(openssl rand -base64 64 | tr -d '\n=+/' | cut -c1-64)

    cat > "${APP_ENV}" <<EOF
# Generated by the PanelAlpha Drupal recipe, once per account.
#
# Read by the app container through env_file: and consumed by
# panelalpha-drupal.php, which writes DRUPAL_HASH_SALT into
# web/sites/default/settings.php on every deploy.
DRUPAL_HASH_SALT=${HASH_SALT}
EOF
  )
fi
chmod 600 "${APP_ENV}"

# ---------------------------------------------------------------------------
# 3. The mount point for the public file system.
#
# The override bind-mounts ${DATA}/files over /app/web/sites/default/files.
# `web/` does not exist yet -- composer has not run -- and if the directory is
# still missing when the container is created, Docker creates the mount point
# itself, as root, inside ~/project. Creating it here as the account leaves a
# directory the deploy's own chown can walk.
#
# Composer is content to install into a web/ that already exists; checked on
# the deploy, `composer/installers` placed drupal/core into web/core beside it.
mkdir -p web/sites/default/files

# ---------------------------------------------------------------------------
# 4. Compose files the repository does not have today.
#
# drupal/recommended-project ships no docker-compose.yml, no compose.yaml and
# no Dockerfile -- checked at 11.x. Were one to appear, the php strategy would
# mine it for backing services and this account would grow whatever database
# upstream's CI uses, beside the one `database: mysql` already provisioned.
#
# Moved by name. Never by a `docker-compose.*.yml` glob: this recipe's own
# override has already been written into the project root by
# AppConfigBootstrap::writeCompose(), which runs before this hook, so a glob
# would eat it and silently strip the env_file, the bind mounts and the
# healthcheck while the deploy still reported success.
mkdir -p "${DATA}/upstream-compose"
for f in docker-compose.yml docker-compose.yaml compose.yml compose.yaml; do
    [ -f "$f" ] || continue
    mv -f "$f" "${DATA}/upstream-compose/"
    echo "[drupal] moved $f out of the checkout"
done

echo "[drupal] prepare finished; state in ${DATA}"
