<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\IPManagement;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('ip_assign')]
#[Description(<<<'MARKDOWN'
    Assign an IP address to a user
    MARKDOWN)]
#[IsDestructive]
class IpAssignTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/ip/assign';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'user_id',
            'username',
            'ip_subnet_id',
            'ip_address',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'user_id' => $schema->integer(),
            'name' => $schema->string(),
            'ip_subnet_id' => $schema->integer()->required(),
            'ip_address' => $schema->string()->required(),
        ];
    }
}
