<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\IPManagement;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('ip_subnet_create')]
#[Description(<<<'MARKDOWN'
    Add an IP subnet
    MARKDOWN)]
#[IsDestructive]
class IpSubnetCreateTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/ip/subnets';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'ip',
            'mask',
            'is_shared',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'ip' => $schema->string()->description('Example: 192.168.1.0.')->required(),
            'mask' => $schema->integer()->required(),
            'is_shared' => $schema->boolean(),
        ];
    }
}
