<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\IPManagement;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('ip_unassign')]
#[Description(<<<'MARKDOWN'
    Unassign an IP address from a project
    MARKDOWN)]
#[IsDestructive]
class IpUnassignTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/ip/unassign';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'ip_subnet_id',
            'ip_address',
            'user_id',
            'username',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'ip_subnet_id' => $schema->integer()->required(),
            'ip_address' => $schema->string()->description('Example: 192.168.1.10.')->required(),
            'user_id' => $schema->integer()->description('Identify the project by id; one of user_id or username is required.'),
            'name' => $schema->string()->description('Identify the project by name; one of user_id or username is required.'),
        ];
    }
}
