<?php

namespace App\Lib\Deploy\Platform;

/**
 * Renders one host-side stage — precheck or prepare — into a standalone shell
 * script the engine drops into the account, runs once, and deletes. `StageScript`
 * is the container's entrypoint, run on every boot; neither can stand in for
 * the other.
 *
 * Command sources are merged manifest first, then the project's own app config,
 * ordered by `before`; `extra` hook scripts always run last.
 */
final class HostScript
{
    /**
     * Is there anything to run for this stage at all?
     *
     * @param array<string, string> $extra
     */
    public static function isEmpty(
        ?PlatformManifest $manifest,
        string $stage,
        ?ProjectContext $context = null,
        array $extra = [],
        array $appConfigCommands = [],
        ?DeployPlan $plan = null
    ): bool {
        // A stage the request named is never "nothing to run", even when it
        // asked for nothing: the script still announces the replacement.
        if (StageResolver::isOverridden($stage, $plan)) {
            return false;
        }

        return $extra === []
            && $appConfigCommands === []
            && self::commandsFor($manifest, $stage, $context) === [];
    }

    /**
     * @param array<string, string> $overrides command id => resolved command
     * @param array<string, string> $extra id => command, appended after
     *        everything else — the app config's legacy hook scripts
     *        (`panelalpha-before-clone-validation.sh`, `panelalpha-after-clone.sh`)
     * @param list<PlatformCommand> $appConfigCommands the app config's staged
     *        commands, merged with the platform's and ordered by `before`
     * @param ?DeployPlan $plan what this deploy was told to run. A stage it
     *        names replaces that stage whole, including `$extra`
     */
    public static function render(
        ?PlatformManifest $manifest,
        string $stage,
        ?ProjectContext $context = null,
        array $overrides = [],
        array $extra = [],
        array $appConfigCommands = [],
        ?DeployPlan $plan = null
    ): string {
        if (!PlatformStage::isHostStage($stage)) {
            throw new \InvalidArgumentException(
                "'{$stage}' does not run on the host; see " . StageScript::class
            );
        }

        $source = $manifest?->source ?? 'the project\'s app config';
        $lines = [
            '#!/bin/bash',
            '# Generated by PanelAlpha for the ' . $stage . ' stage — do not edit.',
            '# Source: ' . $source,
            // `pipefail` so a precheck piping into awk fails on any stage of
            // the pipeline, not only the last one.
            'set -euo pipefail',
            '',
            'pa_step() { printf \'[panelalpha] %s: %s\\n\' "$1" "$2" >&2; }',
            'pa_skip() { printf \'[panelalpha] %s: %s failed (optional, continuing)\\n\' "$1" "$2" >&2; }',
            '',
        ];

        $overridden = StageResolver::isOverridden($stage, $plan);
        if ($overridden) {
            $lines[] = 'pa_step ' . $stage . ' ' . self::quote('replaced by the deploy request');
            $lines[] = '';
        }

        $commands = $overridden
            ? PlatformCommand::ordered($plan?->commandsFor($stage) ?? [])
            : PlatformCommand::ordered(array_merge(
                self::commandsFor($manifest, $stage, $context),
                $context === null ? $appConfigCommands : PlatformMatcher::applicable($appConfigCommands, $context)
            ));

        foreach ($commands as $command) {
            array_push($lines, ...self::renderCommand($command, $stage, $overrides));
        }

        foreach ($overridden ? [] : $extra as $id => $run) {
            array_push($lines, ...self::renderBorrowed((string) $id, $run, $stage));
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * Guards nest as workdir inside timeout, timeout inside the optional `||`.
     *
     * @param array<string, string> $overrides
     * @return list<string>
     */
    private static function renderCommand(PlatformCommand $command, string $stage, array $overrides): array
    {
        $run = $overrides[$command->id] ?? $command->run;
        if ($command->workdir !== null && $command->workdir !== '') {
            $run = '( cd ' . $command->workdir . ' && ' . $run . ' )';
        }
        if ($command->timeout !== null) {
            $run = 'timeout --foreground ' . $command->timeout . ' bash -c ' . self::quote($run);
        }

        $lines = [];
        if ($command->description !== null) {
            // Prefix every line, or a folded multi-line description drops bare
            // shell into the host script (same defect as the entrypoint).
            $lines[] = '# ' . str_replace("\n", "\n# ", $command->description);
        }
        $lines[] = 'pa_step ' . $stage . ' ' . self::quote($command->id);
        $lines[] = $command->optional
            ? $run . ' || pa_skip ' . $stage . ' ' . self::quote($command->id)
            : $run;
        $lines[] = '';

        return $lines;
    }

    /**
     * A script body the engine did not write — an app config's hook — run in a
     * subshell relaxed to plain `set -e`, so third-party scripts keep the
     * failure semantics they were written against.
     *
     * @return list<string>
     */
    private static function renderBorrowed(string $id, string $run, string $stage): array
    {
        return [
            'pa_step ' . $stage . ' ' . self::quote($id),
            '(',
            'set +u +o pipefail',
            // Verbatim and unindented: a heredoc terminator must sit at column
            // 0, and two of the shipped pages use one.
            rtrim($run),
            ')',
            '',
        ];
    }

    /**
     * @return list<PlatformCommand>
     */
    private static function commandsFor(
        ?PlatformManifest $manifest,
        string $stage,
        ?ProjectContext $context
    ): array {
        if ($manifest === null) {
            return [];
        }
        $commands = $manifest->stage($stage);

        return $context === null ? $commands : PlatformMatcher::applicable($commands, $context);
    }

    private static function quote(string $value): string
    {
        return "'" . str_replace("'", "'\\''", $value) . "'";
    }
}
