FROM debian:trixie-slim AS php_prod

RUN apt-get update -y \
    && apt-get install -y \
        lsb-release \
        zip \
        unzip \
        libzip-dev \
        wget \
        lftp \
        libmagickwand-dev \
        libssh2-1-dev \
        libssh2-1 \
        awstats \
        wget \
        curl \
        git \
        rsync \
        sqlite3 \
    && wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg \
    && echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" >/etc/apt/sources.list.d/php.list \
    && apt-get update -y \
    && apt-get install -y \
        php8.4 \
        php8.4-cli \
        php8.4-ftp \
        php8.4-mysql \
        php8.4-opcache \
        php8.4-pdo \
        php8.4-zip \
        php8.4-redis \
        php8.4-imagick \
        php8.4-ssh2 \
        php8.4-curl \
        php8.4-xml \
        php8.4-mbstring \
        php8.4-sqlite3 \
    && sed -i "s/dc_eximconfig_configtype='local'/dc_eximconfig_configtype='internet'/" /etc/exim4/update-exim4.conf.conf \
    && update-exim4.conf

# install docker
RUN apt-get install -y gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
RUN echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update -y
RUN apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

# add www-data to sudoers
RUN apt-get install -y sudo
RUN echo 'www-data ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# apt clean
RUN apt-get clean autoclean \
    && apt-get autoremove -y

WORKDIR /var/www/html

FROM php_prod AS php_debug

RUN apt-get update -y \
    && apt-get install -y \
        nano \
        php8.4-xdebug \
    && echo 'xdebug.mode = coverage' > /etc/php/8.4/cli/conf.d/docker-xdebug.ini

FROM php_prod AS php_nginx_prod

RUN apt-get update -y \
    && apt-get install -y \
        supervisor \
        curl \
        gnupg2 \
        ca-certificates \
        lsb-release \
        debian-archive-keyring

RUN curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor \
    > /usr/share/keyrings/nginx-archive-keyring.gpg

RUN echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] \
    http://nginx.org/packages/debian \
    $(lsb_release -cs) nginx" \
    > /etc/apt/sources.list.d/nginx.list

RUN apt-get update -y \
    && apt-get install -y \
        php8.4-fpm \
        nginx \
    && apt-get clean autoclean \
    && apt-get autoremove -y

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

FROM php_nginx_prod AS php_nginx_debug

RUN apt-get update -y \
    && apt-get install -y \
        nano \
        php8.4-xdebug \
    && echo 'xdebug.mode = coverage' > /etc/php/8.4/cli/conf.d/docker-xdebug.ini \
    && echo 'xdebug.mode = coverage' > /etc/php/8.4/fpm/conf.d/docker-xdebug.ini
