<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Files;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('file_zip')]
#[Description(<<<'MARKDOWN'
    Create a ZIP archive

    Calls POST /api/projects/{username}/files/zip. This changes server state.
    MARKDOWN)]
#[IsDestructive]
class FileZipTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/files/zip';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'zip_path',
            'path',
            'compression_level',
            'from_date',
            'ignore_empty',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('Name of the project. Sent to the API as `username`.')->required(),
            'zip_path' => $schema->string()->description('Example: /public_html/backup.zip.')->required(),
            'path' => $schema->string()->description('Example: /public_html/dir.')->required(),
            'compression_level' => $schema->integer()->description('Example: 6.'),
            'from_date' => $schema->string()->description('Example: 2026-01-01.'),
            'ignore_empty' => $schema->boolean()->description('Example: .'),
        ];
    }
}
