<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Files;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('file_upload')]
#[Description(<<<'MARKDOWN'
    Upload a file

    Stores one file under `path` (e.g. /project). Small: file_name + file_contents. Anything larger: file_url, which the engine downloads.
    MARKDOWN)]
#[IsDestructive]
class FileUploadTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/files/upload';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'path',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function fileParams(): array
    {
        return [
            'file',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'path' => $schema->string()->description('Example: /public_html.')->required(),
            'file_name' => $schema->string()->description('File name, no directories. Required with file_contents; defaults to the URL\'s last segment.'),
            'file_contents' => $schema->string()->description('The bytes, base64 unless file_encoding is text. Small files only.'),
            'file_encoding' => $schema->string()->description('Default base64. One of: base64, text.'),
            'file_url' => $schema->string()->description('http(s) URL the engine downloads instead, e.g. a repository\'s archive/refs/heads/main.zip.'),
        ];
    }
}
