<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Files;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('file_fetch')]
#[Description(<<<'MARKDOWN'
    Fetch an http or https URL into the project

    Calls POST /api/projects/{username}/files/fetch. This changes server state.
    MARKDOWN)]
#[IsDestructive]
class FileFetchTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/files/fetch';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'url',
            'path',
            'filename',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('Name of the project. Sent to the API as `username`.')->required(),
            'url' => $schema->string()->description('Example: https://example.com/plugin.zip.')->required(),
            'path' => $schema->string()->description('Example: /public_html.')->required(),
            'filename' => $schema->string()->description('Example: plugin.zip.'),
        ];
    }
}
