<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\SSH;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('ssh_run')]
#[Description(<<<'MARKDOWN'
    Run a shell command inside the project container

    Runs one command as the project user inside its container, the way an SSH session would — the command line reaches bash intact, so pipes, redirection and globs work. A non-zero exit is reported in the response, not as an HTTP error. Dind projects only.
    MARKDOWN)]
#[IsDestructive]
class SshRunTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/ssh/command';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'command',
            'cwd',
            'timeout',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'command' => $schema->string()->description('Example: ls -la && cat composer.json.')->required(),
            'cwd' => $schema->string()->description('Directory to run in; defaults to the account home directory. Example: /home/demo/project.'),
            'timeout' => $schema->integer()->description('Seconds before the command is killed (1-900, default 300).'),
        ];
    }
}
