<?php

namespace App\Support;

use RuntimeException;
use Symfony\Component\Process\Process;
use Throwable;

/**
 * How many `queue:work` processes core's own supervisord runs.
 *
 * `numprocs` in `config/core/supervisord.conf` used to read
 * `%(ENV_QUEUE_WORKERS)s` directly -- which supervisord resolves against its
 * own process environment, fixed the moment the container starts. Docker
 * never updates a running container's environment, so editing `QUEUE_WORKERS`
 * in `.env-core` changed nothing until the container was recreated, even though
 * `supervisorctl reread` + `update` genuinely does re-parse a changed *file*
 * live. Measured on a real host: `reread` right after that edit reported "No
 * config updates to processes" -- the container's own copy of the variable
 * was still the old value.
 *
 * The fix moves `numprocs` out of that frozen environment and into a plain
 * generated file this class writes with the literal count baked in
 * ({@see GENERATED_CONF}), which `supervisord.conf`'s `[include]` pulls in.
 * Applying a new count writes that file and asks supervisord to re-read it --
 * no container recreate.
 */
class QueueWorkers
{
    public const MIN = 1;

    public const MAX = 32;

    public const DEFAULT = 2;

    /** Where this class writes the live `[program:queue]` block; `supervisord.conf` `[include]`s it. */
    public const GENERATED_CONF = '/etc/supervisor/conf.d/queue.generated.conf';

    /** The `[program:queue]` block, everything but the count. */
    private const TEMPLATE = <<<'CONF'
        ; Generated by App\Support\QueueWorkers -- change the count with
        ; `pae configure queue`, not this file directly; it is overwritten.
        [program:queue]
        command=php /var/www/html/artisan queue:work database --queue=default --sleep=1 --tries=1 --timeout=86500 --memory=256
        process_name=%(program_name)s_%(process_num)02d
        numprocs={{COUNT}}
        ; A worker exits when the DB is down (e.g. core.sqlite not written by the entrypoint yet); never go FATAL for that.
        startsecs=0
        directory=/var/www/html
        user=www-data
        ; supervisord would pass on root's HOME otherwise.
        environment=HOME="/var/www",USER="www-data"
        autostart=true
        autorestart=true
        stdout_logfile=/dev/stdout
        stdout_logfile_maxbytes=0
        redirect_stderr=true

        CONF;

    /** What `.env-core` says the count should be -- what a freshly-recreated container boots with. */
    public static function configured(): int
    {
        $value = EnvFile::current()->get('QUEUE_WORKERS');

        return $value !== null && ctype_digit($value) ? (int) $value : self::DEFAULT;
    }

    /**
     * How many `queue:work` processes are actually running right now, read
     * from supervisord itself rather than assumed from `.env` -- the two
     * differ for exactly as long as a changed count has not been applied.
     * Null when supervisord cannot be reached (also true before its own
     * first start, mid-boot).
     */
    public static function running(): ?int
    {
        try {
            $status = (new Process(['supervisorctl', 'status']))->mustRun()->getOutput();
        } catch (Throwable) {
            return null;
        }

        return substr_count($status, 'queue:queue_');
    }

    /** @return string|null an error, or null when $count is fine */
    public static function badCount(int $count): ?string
    {
        if ($count < self::MIN || $count > self::MAX) {
            return sprintf('Enter a number from %d to %d.', self::MIN, self::MAX);
        }

        return null;
    }

    /**
     * The `[program:queue]` block with $count baked in -- split out from
     * apply() so a test can check what would be written without a
     * filesystem to write it to.
     */
    public static function conf(int $count): string
    {
        return str_replace('{{COUNT}}', (string) $count, self::TEMPLATE);
    }

    /**
     * Write the new count everywhere it needs to land: the generated
     * supervisord program block, and `.env-core` so a future container
     * recreate boots with it too. Reloads supervisord live when it is
     * reachable; silently skipped when it is not -- this also runs from the
     * entrypoint, before supervisord's own first start.
     *
     * @throws RuntimeException if $count is out of range
     */
    public static function apply(int $count): void
    {
        if (($error = self::badCount($count)) !== null) {
            throw new RuntimeException($error);
        }

        EnvFile::current()->set(['QUEUE_WORKERS' => (string) $count]);

        if (file_put_contents(self::GENERATED_CONF, self::conf($count), LOCK_EX) === false) {
            throw new RuntimeException('Could not write ' . self::GENERATED_CONF . '.');
        }

        self::reload();
    }

    private static function reload(): void
    {
        try {
            (new Process(['supervisorctl', 'reread']))->run();
            (new Process(['supervisorctl', 'update']))->run();
        } catch (Throwable) {
            // Not up yet (the entrypoint, before its own first start) or not
            // reachable for some other reason -- the file is still written,
            // and whatever starts supervisord next reads it fresh.
        }
    }
}
