<?php

namespace App\Support;

use RuntimeException;
use Symfony\Component\Process\Process;
use Throwable;

/**
 * How many `queue:work` processes core runs, each its own s6 service
 * (`queue-1` .. `queue-N` under {@see SCAN_DIR}).
 *
 * The count lives in `.env-core`, but Docker freezes a running container's
 * environment, so a changed value cannot reach the running processes through
 * it. Applying a count instead writes one service directory per worker and
 * asks s6-svscan to rescan: new workers start, removed ones get SIGTERM and
 * finish their current job first. No container recreate.
 */
class QueueWorkers
{
    public const MIN = 1;

    public const MAX = 32;

    /** s6-svscan's scan directory; entrypoint-core.sh fills it before starting it. */
    public const SCAN_DIR = '/run/service';

    private const PREFIX = 'queue-';

    /** Below this much host RAM one worker is the default: each holds ~45-90 MB. */
    private const SMALL_HOST_MB = 4096;

    /**
     * A worker restarts after 20 jobs or an hour, whichever is first, so the
     * memory a deploy grew it by is handed back instead of held until
     * --memory. Both are checked between jobs, never during one.
     */
    private const RUN_SCRIPT = <<<'SH'
        #!/bin/sh
        # Generated by App\Support\QueueWorkers -- change the count with
        # `pae configure queue`, not this file directly; it is overwritten.
        cd /var/www/html || exit 1
        exec env HOME=/var/www USER=www-data s6-setuidgid www-data \
            php artisan queue:work database --queue=default --sleep=1 --tries=1 --timeout=86500 \
            --memory=256 --max-jobs=20 --max-time=3600 2>&1

        SH;

    /** What `.env-core` says the count should be, else the default for this host. */
    public static function configured(): int
    {
        $value = EnvFile::current()->get('QUEUE_WORKERS');

        return $value !== null && ctype_digit($value)
            ? (int) $value
            : self::defaultFor((string) @file_get_contents('/proc/meminfo'));
    }

    /** One worker on a host under 4 GB, two otherwise. Unreadable counts as big. */
    public static function defaultFor(string $procMeminfo): int
    {
        if (preg_match('/^MemTotal:\s+(\d+)\s*kB/mi', $procMeminfo, $m) !== 1) {
            return 2;
        }

        return intdiv((int) $m[1], 1024) < self::SMALL_HOST_MB ? 1 : 2;
    }

    /**
     * How many workers s6 reports up right now -- not assumed from `.env`,
     * since the two differ until a changed count is applied. Null when s6 is
     * not running (mid-boot, or an old container still on supervisord).
     */
    public static function running(?string $scanDir = null): ?int
    {
        $scanDir ??= self::SCAN_DIR;
        if (!is_dir($scanDir . '/.s6-svscan')) {
            return null;
        }

        $up = 0;
        foreach (self::serviceDirs($scanDir) as $dir) {
            try {
                $state = (new Process(['s6-svstat', '-o', 'up', $dir]))->mustRun()->getOutput();
            } catch (Throwable) {
                continue;
            }
            if (trim($state) === 'true') {
                $up++;
            }
        }

        return $up;
    }

    /** @return string|null an error, or null when $count is fine */
    public static function badCount(int $count): ?string
    {
        if ($count < self::MIN || $count > self::MAX) {
            return sprintf('Enter a number from %d to %d.', self::MIN, self::MAX);
        }

        return null;
    }

    /** The `run` script every worker service gets. */
    public static function runScript(): string
    {
        return self::RUN_SCRIPT;
    }

    /**
     * Write the count everywhere it needs to land: one service directory per
     * worker, and `.env-core` so a recreated container boots with it too.
     * Tells s6-svscan when it is running; skipped when not -- this also runs
     * from the entrypoint, before s6-svscan starts and scans the directory.
     *
     * @throws RuntimeException if $count is out of range or a service cannot be written
     */
    public static function apply(int $count, ?string $scanDir = null): void
    {
        if (($error = self::badCount($count)) !== null) {
            throw new RuntimeException($error);
        }
        $scanDir ??= self::SCAN_DIR;

        EnvFile::current()->set(['QUEUE_WORKERS' => (string) $count]);

        self::writeServices($count, $scanDir);
        self::rescan($scanDir);
        self::pruneRetired($scanDir);
    }

    /** Workers 1..$count exist with the current script; higher numbers are gone. */
    public static function writeServices(int $count, string $scanDir): void
    {
        for ($i = 1; $i <= $count; $i++) {
            $dir = $scanDir . '/' . self::PREFIX . $i;
            if (!is_dir($dir) && !mkdir($dir, 0755, true) && !is_dir($dir)) {
                throw new RuntimeException("Could not create {$dir}.");
            }
            if (file_put_contents($dir . '/run', self::RUN_SCRIPT, LOCK_EX) === false || !chmod($dir . '/run', 0755)) {
                throw new RuntimeException("Could not write {$dir}/run.");
            }
        }

        // Retire a worker by hiding its directory: s6-svscan ignores dot-names,
        // so the next rescan stops it, and its supervisor still has the
        // directory to write into while the current job finishes.
        foreach (self::serviceDirs($scanDir) as $dir) {
            $number = (int) substr(basename($dir), strlen(self::PREFIX));
            if ($number > $count) {
                // Unique, so a worker retired again never lands on one still finishing a job.
                $retired = $scanDir . '/.' . basename($dir) . '-' . bin2hex(random_bytes(4));
                if (!rename($dir, $retired)) {
                    throw new RuntimeException("Could not retire {$dir}.");
                }
            }
        }
    }

    /** Delete retired workers whose supervisor has gone. */
    private static function pruneRetired(string $scanDir): void
    {
        foreach (glob($scanDir . '/.' . self::PREFIX . '*', GLOB_ONLYDIR) ?: [] as $dir) {
            try {
                $supervised = (new Process(['s6-svok', $dir]))->run() === 0;
            } catch (Throwable) {
                continue;
            }
            if (!$supervised) {
                self::removeTree($dir);
            }
        }
    }

    /** @return list<string> the worker service directories, in number order */
    private static function serviceDirs(string $scanDir): array
    {
        $dirs = glob($scanDir . '/' . self::PREFIX . '*', GLOB_ONLYDIR) ?: [];
        usort($dirs, fn (string $a, string $b): int => strnatcmp($a, $b));

        return $dirs;
    }

    /** -a picks up new directories, -n stops the supervisors of removed ones. */
    private static function rescan(string $scanDir): void
    {
        if (!is_dir($scanDir . '/.s6-svscan')) {
            return;
        }
        try {
            (new Process(['s6-svscanctl', '-an', $scanDir]))->run();
        } catch (Throwable) {
            // The directories are written; the next s6-svscan start reads them.
        }
    }

    private static function removeTree(string $path): void
    {
        if (is_link($path) || !is_dir($path)) {
            @unlink($path);

            return;
        }
        foreach (scandir($path) ?: [] as $item) {
            if ($item !== '.' && $item !== '..') {
                self::removeTree($path . '/' . $item);
            }
        }
        @rmdir($path);
    }
}
