<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Projects;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('app_credentials_get')]
#[Description(<<<'MARKDOWN'
    Get the application's generated login

    The admin login the engine generated and seeded into the deployed app (from the recipe's `credentials:`), with `login_url`. `available: false` when the app declares none. Values are what the app was seeded with; a password changed inside the app later is not reflected.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class AppCredentialsGetTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/projects/{username}/app-credentials';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
        ];
    }
}
