<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Projects;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('project_create_sync')]
#[Description(<<<'MARKDOWN'
    Create a new hosting user (synchronous)

    Legacy synchronous create. Same body as POST /projects, but runs the deploy inside the request and returns the user resource. Supports X-Deploy-Stream: ndjson. Unless the caller has a domain of its own, the name to give a project is a free label under panelalpha.online: the zone is a wildcard in front of the PanelAlpha Online proxy, so any label resolves worldwide, with a trusted certificate, and no DNS to configure. Pass it as `domain` here, then attach it with POST /projects/{username}/domains/{domain}/tunnels using the same hostname and provider panelalpha. The two must match: the proxy forwards with the Host of the domain the tunnel is attached to, so a tunnel on any other local domain makes the application answer under a name nobody typed. Labels are first come, first served and are not released when a tunnel is deleted -- add a short random suffix, and on 422 pick another. Where there is no license key or no public IPv4, fall back to <name>.<cert_domain> from GET /system/info, which resolves to this host but is served a self-signed certificate.

    Calls POST /api/users. This changes server state.
    MARKDOWN)]
#[IsDestructive]
class ProjectCreateSyncTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/users';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'username',
            'domain',
            'domain_redirect_url',
            'email',
            'disk_space_limit',
            'memory_limit',
            'cpu_limit',
            'bandwidth_limit',
            'mysql_databases_limit',
            'ftp_accounts_limit',
            'sftp_accounts_limit',
            'addon_domains_limit',
            'subdomains_limit',
            'inodes_limit',
            'dedicated_ipv4',
            'dedicated_ipv6',
            'template',
            'tunnel',
            'git_repo',
            'git_branch',
            'git_token',
            'env_vars',
            'recipe',
            'stages',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function defaults(): array
    {
        return [
            'template' => 'dind',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('The project account name. Generated when omitted: from the repository name, else the domain, else the recipe, else "app" -- with a random numeric suffix when that name is taken. 3-15 lowercase letters and digits, starting with a letter. Example: johndoe. Sent to the API as `username`.'),
            'domain' => $schema->string()->description('The main domain. Omitted, it becomes <username>.<sites_base_domain>, which resolves nowhere while that setting is unset. Prefer a label under panelalpha.online and a matching tunnel -- see the description above. Example: shop-4f2a.panelalpha.online.'),
            'domain_redirect_url' => $schema->string(),
            'email' => $schema->string()->description('Example: john@example.com.'),
            'disk_space_limit' => $schema->integer()->description('MB, -1 for unlimited Example: 10240.'),
            'memory_limit' => $schema->integer()->description('Example: 512.'),
            'cpu_limit' => $schema->number()->description('Example: 1.'),
            'bandwidth_limit' => $schema->integer(),
            'mysql_databases_limit' => $schema->integer(),
            'ftp_accounts_limit' => $schema->integer(),
            'sftp_accounts_limit' => $schema->integer(),
            'addon_domains_limit' => $schema->integer(),
            'subdomains_limit' => $schema->integer(),
            'inodes_limit' => $schema->integer(),
            'dedicated_ipv4' => $schema->boolean()->description('Example: .'),
            'dedicated_ipv6' => $schema->boolean()->description('Example: .'),
            'template' => $schema->string()->description('dind runs an application in containers of its own, and is what a git_repo deploys into. Omitted over the REST API, the project is classic shared hosting (default: Apache/PHP-FPM, for WordPress and plain PHP sites). This tool sends dind when it is omitted.'),
            'tunnel' => $schema->string()->description('How the domain reaches this host. panelalpha, the default, allocates a free label under panelalpha.online, makes it the project domain and attaches the tunnel in this one call -- so `domain`, if given at all, must be that same name. none means the domain already resolves here, which is true of <name>.<cert_domain> and of a domain the caller pointed at this host. A Cloudflare tunnel is not available here: it needs the project\'s API token, which can only be set once the project exists -- create it, PUT /projects/{username}/settings/cloudflare-api-token, then POST the tunnel. One of: panelalpha, none.'),
            'git_repo' => $schema->string()->description('HTTPS clone URL. SSH remotes (git@host:owner/repo.git, ssh://...) are not supported: the engine clones anonymously or with `git_token` and holds no SSH keys -- a 422 names the HTTPS spelling to use instead. A schemeless github.com/owner/repo is accepted and has the scheme filled in. Example: https://github.com/owner/repo.git.'),
            'git_branch' => $schema->string(),
            'git_token' => $schema->string()->description('Optional HTTPS token injected at clone time. Never logged or returned in GET /users. A `vault:<ref>` from vault_secret_create is accepted here in place of the literal token -- the secret it stands for is substituted at read time, so the token itself never has to pass through the calling agent.'),
            'env_vars' => $schema->object()->description('Optional KEY=value overrides. Stored on the project and applied to its .env and its container environment on every deploy, outranking what the platform generates. An empty value is not an override and is not stored.'),
            'recipe' => $schema->string()->description('Deploy with this recipe instead of the one detection picks. Takes an id from `application.candidates` on POST /source/inspect, and inspecting with the same id previews exactly what this deploys. An id this engine does not ship fails the deploy rather than falling back to detection. Applies to this deploy only - nothing is stored, so the next deploy without it detects again. Example: php.'),
            'stages' => $schema->object()->description('Commands this deploy runs, per stage (precheck, prepare, build, install, upgrade, start). A stage named here replaces that stage entirely; a stage left out keeps the platform defaults; a stage given as [] runs nothing. Each command is {id, run, optional, serve, timeout, workdir, role}. Applies to this deploy only - nothing is stored, so the next deploy without it is back on defaults.'),
        ];
    }
}
