<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Projects;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('project_create')]
#[Description(<<<'MARKDOWN'
    Create a new hosting project (async)

    Creates the account now and deploys it in the background: answers 202 with a task `id`. Poll task_get until it is completed, failed or cancelled. Leave `domain` out: the engine picks the best public name it can, a free panelalpha.online one when available, and project_get says which (details.domain). Resource limits are set afterwards with project_update.
    MARKDOWN)]
#[IsDestructive]
class ProjectCreateTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'username',
            'domain',
            'email',
            'memory_limit',
            'template',
            'tunnel',
            'git_repo',
            'git_branch',
            'git_token',
            'env_vars',
            'recipe',
            'stages',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function defaults(): array
    {
        return [
            'template' => 'dind',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('3-15 lowercase letters and digits, starting with a letter. Generated from the repository or domain when omitted. Example: johndoe.'),
            'domain' => $schema->string()->description('Only for a domain of the user\'s own, with tunnel: none. Omitted, the engine picks the best public name it can. Example: shop-4f2a.panelalpha.online.'),
            'email' => $schema->string()->description('Example: john@example.com.'),
            'memory_limit' => $schema->integer()->description('MB. Default: the server\'s RAM less the engine\'s share, which is also the most allowed.'),
            'template' => $schema->string()->description('dind runs the app in containers of its own; the other templates are classic shared hosting. This tool sends dind when it is omitted.'),
            'tunnel' => $schema->string()->description('panelalpha (default): a free panelalpha.online name with a trusted certificate, tunnel attached in this call. none: `domain` already points at this host. One of: panelalpha, none.'),
            'git_repo' => $schema->string()->description('HTTPS clone URL; SSH remotes are refused. github.com/owner/repo also works. Example: https://github.com/owner/repo.git.'),
            'git_branch' => $schema->string(),
            'git_token' => $schema->string()->description('Token for a private repository. Prefer a `vault:<id>` from vault_secret_create over the token itself.'),
            'env_vars' => $schema->object()->description('KEY=value applied to the app\'s .env and container on every deploy.'),
            'recipe' => $schema->string()->description('Recipe id to use instead of the detected one, from source_inspect\'s application.candidates. This deploy only. Example: php.'),
            'stages' => $schema->object()->description('Replace a stage\'s commands for this deploy only: {stage: [{id, run, ...}]} for precheck, prepare, build, install, upgrade, start; [] skips a stage.'),
        ];
    }
}
