<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Projects;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('project_clone')]
#[Description(<<<'MARKDOWN'
    Clone a project

    Clone a project.

    Creates a new project with the same resource limits and settings as the
    source, derives a staging domain when none is provided, and copies the
    source's home directory (including named Docker volumes) and project config
    files to the new project after provisioning completes.

    Subdomains, FTP/SFTP accounts, MySQL databases/users and dedicated IP
    addresses are NOT cloned.
    MARKDOWN)]
#[IsDestructive]
class ProjectCloneTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/clone';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'new_username',
            'domain',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
            'new_name' => 'new_username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('Source project\'s name.')->required(),
            'new_name' => $schema->string()->description('Sent to the API as `new_username`.'),
            'domain' => $schema->string(),
        ];
    }
}
