<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Projects;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;

#[Name('project_update')]
#[Description(<<<'MARKDOWN'
    Update a project
    MARKDOWN)]
#[IsDestructive]
#[IsIdempotent]
class ProjectUpdateTool extends ApiTool
{
    protected function method(): string
    {
        return 'PUT';
    }

    protected function path(): string
    {
        return '/projects/{username}';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'domain',
            'email',
            'disk_space_limit',
            'memory_limit',
            'cpu_limit',
            'bandwidth_limit',
            'mysql_databases_limit',
            'ftp_accounts_limit',
            'sftp_accounts_limit',
            'addon_domains_limit',
            'subdomains_limit',
            'inodes_limit',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'domain' => $schema->string(),
            'email' => $schema->string(),
            'disk_space_limit' => $schema->integer(),
            'memory_limit' => $schema->integer()->description('MB. Can be changed, not removed. Refused when larger than memory_budget.max_project_mb in GET /metrics/current'),
            'cpu_limit' => $schema->number(),
            'bandwidth_limit' => $schema->integer(),
            'mysql_databases_limit' => $schema->integer(),
            'ftp_accounts_limit' => $schema->integer(),
            'sftp_accounts_limit' => $schema->integer(),
            'addon_domains_limit' => $schema->integer(),
            'subdomains_limit' => $schema->integer(),
            'inodes_limit' => $schema->integer(),
        ];
    }
}
