<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Projects;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('project_create_sync')]
#[Description(<<<'MARKDOWN'
    Create a new hosting project (synchronous)

    Legacy synchronous create. Same body as POST /projects, but runs the deploy inside the request and returns the project resource. Supports X-Deploy-Stream: ndjson. Unless the caller has a domain of its own, the name to give a project is a free label under panelalpha.online: the zone is a wildcard in front of the PanelAlpha Online proxy, so any label resolves worldwide, with a trusted certificate, and no DNS to configure. Pass it as `domain` here, then attach it with POST /projects/{username}/domains/{domain}/tunnels using the same hostname and provider panelalpha. The two must match: the proxy forwards with the Host of the domain the tunnel is attached to, so a tunnel on any other local domain makes the application answer under a name nobody typed. Labels are first come, first served and are not released when a tunnel is deleted -- add a short random suffix, and on 422 pick another. Where there is no license key or no public IPv4, fall back to <name>.<cert_domain> from GET /system/info, which resolves to this host but is served a self-signed certificate.
    MARKDOWN)]
#[IsDestructive]
class ProjectCreateSyncTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/users';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'username',
            'domain',
            'domain_redirect_url',
            'email',
            'disk_space_limit',
            'memory_limit',
            'cpu_limit',
            'bandwidth_limit',
            'mysql_databases_limit',
            'ftp_accounts_limit',
            'sftp_accounts_limit',
            'addon_domains_limit',
            'subdomains_limit',
            'inodes_limit',
            'dedicated_ipv4',
            'dedicated_ipv6',
            'template',
            'tunnel',
            'git_repo',
            'git_branch',
            'git_token',
            'env_vars',
            'recipe',
            'stages',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function defaults(): array
    {
        return [
            'template' => 'dind',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('3-15 lowercase letters and digits, starting with a letter. Generated from the repository or domain when omitted. Example: johndoe.'),
            'domain' => $schema->string()->description('Only for a domain of the user\'s own, with tunnel: none. Omitted, the engine picks the best public name it can. Example: shop-4f2a.panelalpha.online.'),
            'domain_redirect_url' => $schema->string(),
            'email' => $schema->string()->description('Example: john@example.com.'),
            'disk_space_limit' => $schema->integer()->description('MB, -1 for unlimited'),
            'memory_limit' => $schema->integer()->description('MB. Default: the server\'s RAM less the engine\'s share, which is also the most allowed.'),
            'cpu_limit' => $schema->number(),
            'bandwidth_limit' => $schema->integer(),
            'mysql_databases_limit' => $schema->integer(),
            'ftp_accounts_limit' => $schema->integer(),
            'sftp_accounts_limit' => $schema->integer(),
            'addon_domains_limit' => $schema->integer(),
            'subdomains_limit' => $schema->integer(),
            'inodes_limit' => $schema->integer(),
            'dedicated_ipv4' => $schema->boolean(),
            'dedicated_ipv6' => $schema->boolean(),
            'template' => $schema->string()->description('dind runs the app in containers of its own; the other templates are classic shared hosting. This tool sends dind when it is omitted.'),
            'tunnel' => $schema->string()->description('panelalpha (default): a free panelalpha.online name with a trusted certificate, tunnel attached in this call. none: `domain` already points at this host. One of: panelalpha, none.'),
            'git_repo' => $schema->string()->description('HTTPS clone URL; SSH remotes are refused. github.com/owner/repo also works. Example: https://github.com/owner/repo.git.'),
            'git_branch' => $schema->string(),
            'git_token' => $schema->string()->description('Token for a private repository. Prefer a `vault:<id>` from vault_secret_create over the token itself.'),
            'env_vars' => $schema->object()->description('KEY=value applied to the app\'s .env and container on every deploy.'),
            'recipe' => $schema->string()->description('Recipe id to use instead of the detected one, from source_inspect\'s application.candidates. This deploy only. Example: php.'),
            'stages' => $schema->object()->description('Replace a stage\'s commands for this deploy only: {stage: [{id, run, ...}]} for precheck, prepare, build, install, upgrade, start; [] skips a stage.'),
        ];
    }
}
