<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Projects;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('project_rebuild')]
#[Description(<<<'MARKDOWN'
    Redeploy a project

    Detects, builds and starts the app again from ~/project, importing `zip_path` first when given (refused on a git project). Answers when the deploy ends; if the call times out the deploy carries on, so follow deploy_log_get instead of calling again.
    MARKDOWN)]
#[IsDestructive]
class ProjectRebuildTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/rebuild';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'env_vars',
            'zip_path',
            'recipe',
            'stages',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'env_vars' => $schema->object()->description('KEY=value changes merged onto the project\'s; an empty value removes a key, null clears them all.'),
            'zip_path' => $schema->string()->description('Optional archive under the project home to import into ~/project before detect/apply'),
            'recipe' => $schema->string()->description('Recipe id to use instead of the detected one, from source_inspect\'s application.candidates. This deploy only. Example: php.'),
            'stages' => $schema->object()->description('Replace a stage\'s commands for this deploy only: {stage: [{id, run, ...}]} for precheck, prepare, build, install, upgrade, start; [] skips a stage.'),
        ];
    }
}
