<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Firewall;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('firewall_log_list')]
#[Description(<<<'MARKDOWN'
    Read what the firewall blocked and banned

    Newest first. blocked: a connection refused by the default policy (on a published port too), as the kernel logged it, rate-limited. ban/unban: fail2ban banning or releasing an address. A connection dropped by an explicit deny rule is not logged.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class FirewallLogListTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/firewall/logs';
    }

    /**
     * @return array<int, string>
     */
    protected function queryParams(): array
    {
        return [
            'limit',
            'type',
            'address',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'limit' => $schema->integer(),
            'type' => $schema->string()->description('One of: blocked, ban, unban.'),
            'address' => $schema->string()->description('Only entries for this IPv4 or IPv6 address.'),
        ];
    }
}
