<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Firewall;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('firewall_trusted_list')]
#[Description(<<<'MARKDOWN'
    List trusted addresses

    Addresses the login protection (fail2ban) never bans: failed SSH, SFTP, FTP and engine API logins from them are not counted. They are not allow rules; the firewall rules still apply to them.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class FirewallTrustedListTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/firewall/trusted';
    }



    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [];
    }
}
