<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Firewall;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('firewall_rule_create')]
#[Description(<<<'MARKDOWN'
    Add a firewall rule

    A deny rule is placed above every allow rule, so it wins; an allow rule goes last. A rule needs a port, a source or a destination. Do not open a port for an application: sites are reached through the engine's webserver.
    MARKDOWN)]
#[IsDestructive]
class FirewallRuleCreateTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/firewall/rules';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'action',
            'direction',
            'protocol',
            'port',
            'source',
            'destination',
            'comment',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'action' => $schema->string()->description('One of: allow, deny.')->required(),
            'direction' => $schema->string()->description('Default in. both: traffic from source coming in and to source going out, as one rule; needs source and no destination. One of: in, out, both.'),
            'protocol' => $schema->string()->description('Omit for both. Required with a port range or list. One of: tcp, udp.'),
            'port' => $schema->string()->description('Destination port, range (30000:30009) or comma list. Example: 22.'),
            'source' => $schema->string()->description('IPv4/IPv6 address or CIDR. Omit for any. Example: 203.0.113.7.'),
            'destination' => $schema->string()->description('IPv4/IPv6 address or CIDR. Omit for any.'),
            'comment' => $schema->string(),
        ];
    }
}
