<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Firewall;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;

#[Name('firewall_rule_update')]
#[Description(<<<'MARKDOWN'
    Edit a firewall rule

    A field not sent keeps its current value; send null to clear it. The rule gets a new id when what it matches changes.
    MARKDOWN)]
#[IsDestructive]
#[IsIdempotent]
class FirewallRuleUpdateTool extends ApiTool
{
    protected function method(): string
    {
        return 'PUT';
    }

    protected function path(): string
    {
        return '/firewall/rules/{id}';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'id',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'action',
            'direction',
            'protocol',
            'port',
            'source',
            'destination',
            'comment',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'id' => $schema->string()->required(),
            'action' => $schema->string()->description('One of: allow, deny.'),
            'direction' => $schema->string()->description('One of: in, out, both.'),
            'protocol' => $schema->string()->description('One of: tcp, udp.'),
            'port' => $schema->string(),
            'source' => $schema->string(),
            'destination' => $schema->string(),
            'comment' => $schema->string(),
        ];
    }
}
