<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Firewall;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('firewall_trusted_add')]
#[Description(<<<'MARKDOWN'
    Trust an address

    It is never banned again, and a ban it has now is lifted. Trust your own office, monitoring, or the panel that calls this engine, so a mistyped password or a stale token cannot lock it out.
    MARKDOWN)]
#[IsDestructive]
class FirewallTrustedAddTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/firewall/trusted';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'address',
            'comment',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'address' => $schema->string()->description('IPv4/IPv6 address or CIDR. Example: 203.0.113.7.')->required(),
            'comment' => $schema->string()->description('Example: office.'),
        ];
    }
}
