<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Firewall;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('firewall_rule_create')]
#[Description(<<<'MARKDOWN'
    Add a firewall rule

    A deny rule is placed above every allow rule, so it wins; an allow rule goes last. An inbound deny covers the host's ports and the ports Docker publishes (scope both, as a fail2ban ban does) unless scope published is asked for. A rule needs a port, a source or a destination. A rule that matches the same traffic as one already there, whatever its action or comment, is refused naming that rule, which is left as it is. Do not open a port for an application: sites are reached through the engine's webserver.
    MARKDOWN)]
#[IsDestructive]
class FirewallRuleCreateTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/firewall/rules';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'action',
            'scope',
            'direction',
            'protocol',
            'port',
            'source',
            'destination',
            'comment',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'action' => $schema->string()->description('One of: allow, deny.')->required(),
            'scope' => $schema->string()->description('Default host: the host\'s own ports. published: ports Docker publishes; port and destination are the container\'s, and direction is in. Neither scope reaches the other. An inbound deny without scope published is both. One of: host, published, both.'),
            'direction' => $schema->string()->description('Default in. both: traffic from source coming in and to source going out, as one rule; needs source and no destination. One of: in, out, both.'),
            'protocol' => $schema->string()->description('Omit for both. Required with a port range or list. One of: tcp, udp.'),
            'port' => $schema->string()->description('Destination port, range (30000:30009) or comma list. Example: 22.'),
            'source' => $schema->string()->description('IPv4/IPv6 address or CIDR. Omit for any. Example: 203.0.113.7.'),
            'destination' => $schema->string()->description('IPv4/IPv6 address or CIDR. Omit for any.'),
            'comment' => $schema->string()->description('One line, without \'. Also refused, as ufw would read it as part of the rule: a comment that is only in, out, log or log-all, and on an incoming deny or a published-port rule, delete or in or out followed by more words.'),
        ];
    }
}
