<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Firewall;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('firewall_rule_list')]
#[Description(<<<'MARKDOWN'
    List firewall rules

    In the order the firewall evaluates them. Rules marked managed are the ports the engine itself needs. Host rules by default; scope=published lists the rules for ports Docker publishes. A deny in both scopes is in both lists, once, with scope both.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class FirewallRuleListTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/firewall/rules';
    }

    /**
     * @return array<int, string>
     */
    protected function queryParams(): array
    {
        return [
            'scope',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'scope' => $schema->string()->description('host: the host\'s own ports. published: ports Docker publishes, matched on the container\'s port. One of: host, published.'),
        ];
    }
}
