<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\DomainPHP;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;

#[Name('domain_php_directives_set')]
#[Description(<<<'MARKDOWN'
    Replace domain PHP directives

    Calls PUT /api/domains/{domain}/php-directives. This changes server state.
    MARKDOWN)]
#[IsDestructive]
#[IsIdempotent]
class DomainPhpDirectivesSetTool extends ApiTool
{
    protected function method(): string
    {
        return 'PUT';
    }

    protected function path(): string
    {
        return '/domains/{domain}/php-directives';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'domain',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'settings',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'domain' => $schema->string()->required(),
            'settings' => $schema->object()->description('Example: {"memory_limit":"256M"}.')->required(),
        ];
    }
}
