#!/bin/bash
# Runs in the account shell after the clone and after overrides/ and files/ are
# in place, before `docker compose up`. Two jobs the compose file cannot do for
# itself: generate the first-admin credentials once into a place a redeploy will
# not wipe, and make sure the .env the compose references exists.
#
# NOTE ON SECRETS: Slink's own APP_SECRET, JWT keypair/passphrase and Mercure
# secret are generated by the image's init-secrets script into /app/var/data/keys
# and persist on the slink-data named volume, so this hook does NOT manage them.
# The only credential we own is the admin login.
set -e
cd ~/project

say() { echo "[slink] $*" >&2; }

# ~/.panelalpha survives a redeploy; ~/project is emptied every deploy
# (engine#173). The admin password written under ~/project would be regenerated
# on every rebuild; on a rebuild that reuses the SQLite volume the app would
# ignore it (admin already exists) and the recorded password would no longer
# match the one in the DB. So it lives here and stays stable.
STORE_DIR="${HOME}/.panelalpha/slink"
ENV_FILE="${STORE_DIR}/admin.env"
NOTE="${STORE_DIR}/credentials.txt"

mkdir -p "${STORE_DIR}"
chmod 700 "${HOME}/.panelalpha" "${STORE_DIR}"

# First deploy only. The env file's presence is the "already initialised" flag.
# base64 stripped of +/=/newline so a POSIX env file reads it back verbatim and
# the value carries no character the app's login form or a shell would mangle.
if [ ! -f "${ENV_FILE}" ]; then
    ADMIN_USERNAME="admin"
    ADMIN_EMAIL="admin@slink.local"
    ADMIN_PASSWORD="$(openssl rand -base64 24 | tr -d '\n=/+')"
    (
        umask 077
        cat > "${ENV_FILE}" <<EOF
# Written once on the first deploy and never regenerated. Slink's boot sequence
# (slink:boot -> AdminUserStep) creates the admin from these on the very first
# boot, when no admin exists yet; afterwards the admin lives in the SQLite DB on
# the slink-data volume and this is just the record of the login. Do not delete.
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF
        cat > "${NOTE}" <<EOF
Slink on this account
=====================

Slink is a self-hosted image-sharing platform. All shares are private by
default -- an image is reachable only by whoever holds its share link. Uploading
and the admin dashboard require a login; public self-registration is turned OFF
on this deploy, so only accounts an admin creates can sign in.

ADMIN LOGIN (created once, on the first deploy)
  URL:      <this account's URL>/
  Email:    ${ADMIN_EMAIL}
  Username: ${ADMIN_USERNAME}
  Password: ${ADMIN_PASSWORD}

  Log in with the EMAIL and password. This replaces any shipped default. Change
  it from the app after first login if you like; a redeploy will not reset it
  (the admin lives in the SQLite DB on a named volume, and the bootstrap only
  runs when no admin exists yet).

DATA
  The SQLite databases (admin + all metadata) live under /app/var/data and the
  uploaded images under /app/slink/images, each on its own named Docker volume,
  so both survive redeploy and storage reclaim. The app's signing secrets
  (APP_SECRET, JWT keypair, Mercure secret) are generated by the image into
  /app/var/data/keys on first boot and persist on the same volume.

REGISTRATION
  USER_ALLOW_REGISTRATION is false and USER_APPROVAL_REQUIRED is true. To open
  the instance to other users, flip USER_ALLOW_REGISTRATION on; approved users
  then get their own private space (every user sees only their own images).

CREDENTIALS FILE
  This password lives in ${STORE_DIR} (0600). Do not delete this directory.
EOF
    )
    chmod 600 "${ENV_FILE}" "${NOTE}"
    say "admin credentials written to ${ENV_FILE}; notes in ${NOTE}"
else
    say "reusing the admin credentials in ${ENV_FILE}"
fi

# The compose slink service lists ~/project/.env as an env_file; make sure it
# exists even when the platform has not written one yet, so `docker compose up`
# does not abort on a missing file. The account's env_vars are merged in.
touch .env

# Pre-pull the pinned image so `compose up` starts fast (best effort).
docker pull anirdev/slink:v1.13.1 >/dev/null 2>&1 || true
say "prepare complete"
