#!/bin/bash
# Runs in the account shell after the clone and after overrides/ and files/ are
# in place, before `docker compose up`. The first-admin login is the engine's
# (`credentials:` in panelalpha.yaml), written to ~/.panelalpha/app-credentials.env
# before this hook runs; this only makes sure the .env the compose references
# exists.
#
# NOTE ON SECRETS: Slink's own APP_SECRET, JWT keypair/passphrase and Mercure
# secret are generated by the image's init-secrets script into /app/var/data/keys
# and persist on the slink-data named volume, so this hook does NOT manage them.
set -e
cd ~/project

say() { echo "[slink] $*" >&2; }

# The compose slink service lists ~/project/.env as an env_file; make sure it
# exists even when the platform has not written one yet, so `docker compose up`
# does not abort on a missing file. The account's env_vars are merged in.
touch .env

# Pre-pull the pinned image so `compose up` starts fast (best effort).
docker pull anirdev/slink:v1.13.1 >/dev/null 2>&1 || true
say "prepare complete"
