#!/bin/bash
# Account shell, after the clone and before the build. Runs on every deploy.
#
# Everything here exists because the clone is destructive: GitRepository's
# ProjectTree::clearContents() empties ~/project before every deploy (engine
# #173), and Dolibarr keeps its configuration, its documents and any external
# module *inside* the tree it is served from. So the state lives in
# ~/.panelalpha/dolibarr and the checkout gets links to it.
set -e
cd ~/project

STORE="${HOME}/.panelalpha"
# The account home is root-owned 755, so this is created rather than written
# into $HOME directly.
mkdir -p "${STORE}"
chmod 700 "${STORE}"

DATA="${STORE}/dolibarr"
APP_ENV="${STORE}/dolibarr-app.env"
CREDS="${STORE}/dolibarr-admin-credentials.txt"

# The path the *container* sees. The compose override bind-mounts ${DATA}
# there; /app/htdocs/conf/conf.php is a link to a file under it, so the link
# target is written in the container's terms and reads as dangling over SFTP.
# That is the cost of keeping one copy of conf.php instead of two, and it is
# why the README beside it says where the real file is.
MOUNT="/data"

# ---------------------------------------------------------------------------
# 1. The account's data, outside the checkout.
#
#   documents/  DOL_DATA_ROOT: every attachment, generated PDF, the ECM tree,
#               and install.lock. Dolibarr's default is <htdocs>/../documents,
#               which the next deploy would delete along with the invoices.
#   custom/     $dolibarr_main_document_root_alt, where Dolibarr installs
#               external modules from its own module manager.
#   conf.php    the database password, the instance unique id and the dolcrypt
#               seed. Rotating that id would make everything the account has
#               encrypted unreadable, so it is generated once and kept here.
#
# Created here rather than by Docker: compose creates a missing bind-mount
# source itself, owned by root at mode 755, and this container runs as the
# account uid — which could then write none of it.
mkdir -p "${DATA}/documents" "${DATA}/custom"
chmod 700 "${DATA}" "${DATA}/documents" "${DATA}/custom"

# An empty conf.php is what Dolibarr calls "not configured yet"
# (install/inc.php:207 tests filesize > 8), and step1.php:219 refuses to run
# at all unless the file already exists and is writable.
if [ ! -f "${DATA}/conf.php" ]; then
    (umask 077; : > "${DATA}/conf.php")
fi
chmod 600 "${DATA}/conf.php"

cat > "${DATA}/README.txt" <<EOF
This directory is your Dolibarr account's data. It is deliberately outside
~/project, because every deploy empties ~/project before cloning.

  conf.php     Dolibarr's configuration: database credentials, the instance
               unique id and the encryption seed. ~/project/htdocs/conf/conf.php
               is a symbolic link to this file. The link reads as broken from
               outside the application container, where it points at ${MOUNT};
               inside the container ${MOUNT} is this directory.
  documents/   DOL_DATA_ROOT. Attachments, generated PDFs, the ECM tree and
               install.lock. Back this up together with the database.
  custom/      external modules installed from Dolibarr's module manager.

The database itself is the account's own MySQL database (visible in the panel
and in phpMyAdmin), not a container. Backing up that database and this
directory backs up the whole application.
EOF
chmod 600 "${DATA}/README.txt"

# ---------------------------------------------------------------------------
# 2. The administrator password.
#
# Generated once per account and delivered by `env_file:` at a path that
# climbs out of the checkout. Not through .env: ProjectEnvironment::apply()
# copies .env to .env.default at mode 644 (engine #173), and this is the
# login to an ERP on a public HTTPS domain.
if [ ! -f "${APP_ENV}" ]; then
  (
    umask 077
    # A-Za-z0-9 only, 24 characters. Dolibarr's own form asks for at least 8;
    # the value also travels as a positional argv to step5.php, where a shell
    # metacharacter would be one escaping bug away from a bad day.
    ADMIN_PASS=$(openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | cut -c1-24)
    cat > "${APP_ENV}" <<EOF
# Generated by the PanelAlpha Dolibarr recipe, once per account.
# Read by the app container through env_file:, and consumed by
# panelalpha-dolibarr-setup.php on the install stage, which hands it to
# Dolibarr's own step5.php to create the administrator.
#
# Changing the password inside Dolibarr does not update this file, and the
# setup script never resets a password that already exists.
DOLI_ADMIN_LOGIN=admin
DOLI_ADMIN_PASS=${ADMIN_PASS}
EOF
  )
fi
chmod 600 "${APP_ENV}"

# The copy an account owner can find, at the same mode, in the same place as
# everything else this recipe writes.
cat > "${CREDS}" <<EOF
Dolibarr — administrator account

  URL:       https://<your domain>/
  login:     $(sed -n 's/^DOLI_ADMIN_LOGIN=//p' "${APP_ENV}")
  password:  $(sed -n 's/^DOLI_ADMIN_PASS=//p' "${APP_ENV}")

Generated once per account by the PanelAlpha Dolibarr recipe, which completes
Dolibarr's install wizard from the command line before the site is reachable.
Without that, the wizard is open to whoever loads the page first — it takes an
administrator password from them, with no authentication of any kind, and they
would own the ERP.

Change this password in Dolibarr (Home > Users & Groups > admin) and this file
stops being true.

Your data is the account's MySQL database plus ~/.panelalpha/dolibarr — see the
README.txt there.
EOF
chmod 600 "${CREDS}"

# ---------------------------------------------------------------------------
# 3. The two links into the checkout.
#
# htdocs/conf/conf.php: htdocs/filefunc.inc.php:125 sets $conffile to the
# literal "conf/conf.php" and include_once's it, and install/inc.php:73 does
# the same with "../conf/conf.php". Neither reads an environment variable, and
# the only other supported location is the packagers' /etc/dolibarr/conf.php,
# which is a path inside the image. So a link is how this file lives outside a
# directory that is deleted every deploy. fopen(..., "w") in
# step1.php:912 follows it, so the wizard writes straight through to the store.
ln -sfn "${MOUNT}/conf.php" htdocs/conf/conf.php

# htdocs/custom: Dolibarr's module manager unzips external modules here and
# conf.php names it as $dolibarr_main_document_root_alt. Upstream ships the
# directory holding a README and a .gitignore and nothing else, so replacing it
# with a link loses nothing. Apache follows it because apache-vhost.stub gives
# the document root `Options +FollowSymLinks`.
rm -rf htdocs/custom
ln -sfn "${MOUNT}/custom" htdocs/custom

# ---------------------------------------------------------------------------
# 4. The document root's .htaccess.
#
# htdocs/ ships none — only htdocs/conf/ and htdocs/includes/ do — so this
# creates one. apache-vhost.stub gives the document root `AllowOverride All`,
# which is what makes any of it work.
#
# mod_alias, not mod_rewrite: nothing else in this tree writes rewrite rules,
# and a RedirectMatch cannot be undone by a later [L].
cat > htdocs/.htaccess <<'EOF'
# Written by the PanelAlpha Dolibarr recipe. Recreated on every deploy.

<IfModule mod_alias.c>
    # The install and upgrade wizard, denied outright.
    #
    # panelalpha-dolibarr-setup.php creates install.lock in DOL_DATA_ROOT on
    # the install stage and install/inc.php:319-335 refuses every page here
    # while it exists — so the application already closes itself, and this
    # says it a second way that does not depend on a file on a bind mount.
    #
    # It also covers the part the lock does not. install/upgrade.php and
    # install/upgrade2.php run schema migrations and have no authentication of
    # their own; upstream gates them on an `upgrade.unlock` file instead. And
    # install/phpinfo.php is phpinfo(). The recipe runs the migration itself on
    # the upgrade stage, before Apache binds, which is what makes denying the
    # URL safe rather than a lock-out.
    RedirectMatch 403 ^/install(/.*)?$

    # conf/ already carries upstream's own `Require host localhost`, which
    # depends on a reverse lookup of the client address. This does not depend
    # on anything: the file behind this URL is the database password.
    RedirectMatch 403 ^/conf(/.*)?$

    # includes/ is the vendor tree — composer.json.disabled points Composer's
    # vendor-dir at it. Upstream's includes/.htaccess sets `SetHandler !`,
    # which stops the PHP being *executed* and leaves it being *served*, as
    # source. The JavaScript and CSS under it are still reached by rendered
    # pages, so only .php is denied.
    RedirectMatch 403 ^/includes/.*\.php$

    # public/test/ is four developer pages that upstream ships with
    # `define("NOLOGIN", '1')`, so they answer to anybody.
    #
    # Two of them guard themselves — test_exec.php and test_sessionlock.php
    # refuse unless conf.php sets $dolibarr_main_test, and test_exec.php's
    # body is an `exec('cat /test.txt; ls /dev/std*; ...')` and a clamdscan.
    # Measured: they answer "Access forbidden ..." with **HTTP 200**, so a
    # status code says they are fine and the body says otherwise.
    #
    # The other two do not guard themselves at all. test_csrf.php and
    # test_arrays.php each render a full 22 KB Dolibarr page to an anonymous
    # visitor. Nothing about a hosting account wants them, and the guard on
    # the first two is one conf.php edit away from being off.
    #
    # Everything else under public/ is public on purpose — the online payment
    # pages, the ticket form, the survey module — and is left alone.
    RedirectMatch 403 ^/public/test(/.*)?$
</IfModule>
EOF
chmod 644 htdocs/.htaccess

# ---------------------------------------------------------------------------
# 5. Compose files the repository does not have at its root today.
#
# It ships one at dev/build/docker/docker-compose.yml — a development stack
# with a MariaDB whose password comes from the developer's shell — but nothing
# reads it: RuntimeSidecars only looks at the project root
# (ComposeFileInspector::COMPOSE_FILE_CANDIDATES), and a manifest declaring
# `database:` skips sidecar mining altogether (PhpStrategy.php:64-67).
#
# Moved by name and never by a `docker-compose.*.yml` glob, which would match
# this recipe's own override and take the healthcheck and the /data mount with
# it while the deploy still reported success.
mkdir -p "${STORE}/upstream-compose"
for f in docker-compose.yml docker-compose.yaml compose.yml compose.yaml; do
    [ -f "$f" ] || continue
    mv -f "$f" "${STORE}/upstream-compose/"
    echo "[dolibarr] moved $f out of the checkout"
done

echo "[dolibarr] prepare finished; data directory ${DATA}"
