<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Domains;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('domain_mail_dns_get')]
#[Description(<<<'MARKDOWN'
    List and check the mail DNS records of a domain

    The SPF, DKIM, DMARC and MX records mail sent from this domain through this host needs. With a relay sender domain set, mail is sent as that domain, and the records are its. With check=1 each record is looked up and gets a status: ok, missing, wrong or unknown. The engine does not sign mail; DKIM comes from a relay, whose selector dkim_selector checks.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class DomainMailDnsGetTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/projects/{username}/domains/{domain}/mail-dns';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
            'domain',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function queryParams(): array
    {
        return [
            'check',
            'dkim_selector',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'domain' => $schema->string()->required(),
            'check' => $schema->boolean()->description('Look the records up in DNS.'),
            'dkim_selector' => $schema->string()->description('The DKIM selector the relay signs with, to check its key.'),
        ];
    }
}
