<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Domains;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('ssl_cert_request')]
#[Description(<<<'MARKDOWN'
    Request a Let's Encrypt certificate for a domain

    Gets and installs a Let's Encrypt certificate over HTTP-01, without downtime. The domain must already resolve to this host.
    MARKDOWN)]
#[IsDestructive]
class SslCertRequestTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/domains/{domain}/request-ssl-cert';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
            'domain',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'staging',
            'dry_run',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'domain' => $schema->string()->required(),
            'staging' => $schema->boolean()->description('Untrusted test certificate; spends no rate limit.'),
            'dry_run' => $schema->boolean()->description('Only report whether a request would work.'),
        ];
    }
}
