<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\DomainLogFiles;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('domain_log_download')]
#[Description(<<<'MARKDOWN'
    Download a domain log file
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class DomainLogDownloadTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/projects/{username}/domains/{domain}/log-files/{filename}';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
            'domain',
            'filename',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    protected function returnsFile(): bool
    {
        return true;
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'domain' => $schema->string()->required(),
            'filename' => $schema->string()->required(),
            'offset' => $schema->integer()->min(0)->description('Byte to start reading at. Default 0; pass the previous result\'s next_offset to continue.'),
            'length' => $schema->integer()->min(1)->max(49152)->description('Bytes to read, at most 49152 (the default). The result says whether there is `more`.'),
        ];
    }
}
