<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\BugReports;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('bug_report_create')]
#[Description(<<<'MARKDOWN'
    File a bug report about a deployed application

    Sends a bug report to PanelAlpha through the same telemetry channel the install events use: the report is queued in the local spool and delivered by the next `telemetry:ship` run, so a 201 means "accepted and queued", not "delivered". The response carries the exact redacted report that will be transmitted, so a caller can show it before or after filing. A report is always about one `project`, and the engine gathers the evidence itself rather than asking anyone to paste it: `app.inspect` is the same report GET /projects/{username}/inspect answers with (what the engine detects the application to be, what it would build, which ports it would publish, and the drift between that and what the last deploy froze); `app.health` is a live probe of every published port from inside the account container, with the checks that ask whether what answered is the application at all; `deploy` is what the last deploy decided; `log_tail` is the end of its deploy log at telemetry tier 2. The health probe is the only part that costs seconds and touches the container — turn it off with `attach_health: false`. Everything gathered is redacted before it leaves: tokens, credentials, email addresses, public IPs and home directory paths are masked wherever they appear, and any value under a key naming a secret is replaced outright. `contact` is the one exception and the one field that identifies a person: it is sent exactly as given, is never filled in automatically, and is omitted entirely when not supplied. Requires telemetry to be enabled (`TELEMETRY_ENABLED`, `TELEMETRY_BUG_REPORTS`) and a monitoring host to be configured; otherwise the call fails rather than dropping the report.

    Calls POST /api/bug-reports. This changes server state.
    MARKDOWN)]
#[IsDestructive]
class BugReportCreateTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/bug-reports';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'title',
            'description',
            'severity',
            'area',
            'project',
            'contact',
            'attach_log',
            'attach_health',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'project',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'title' => $schema->string()->description('One-line headline. Reports are grouped across installs by this plus `area`, so write the symptom rather than the incident: numbers, paths and ids inside it are normalised away before grouping. Example: Next.js deploys succeed but the site answers 502.')->required(),
            'description' => $schema->string()->description('What happened, what was expected, and how to reproduce it. Redacted, and capped at 8000 bytes. Example: Deploying a stock create-next-app repo finishes green, but the domain answers 502 until the container is restarted by hand. Engine 1.0.23, Debian 12, sysbox-runc.')->required(),
            'severity' => $schema->string()->description('How badly this hurts. Anything unrecognised becomes "normal". One of: low, normal, high, critical.'),
            'area' => $schema->string()->description('Which part of the engine, as a slug. An open set — the listed values are the ones worth suggesting, not the ones allowed, and anything unrecognised becomes "other". One of: deploy, domains, ssl, dns, mysql, mail, files, backup, containers, metrics, api, mcp, cli, install, panel, other. Example: deploy.'),
            'name' => $schema->string()->description('The application this report is about. Required — a bug report carries that project\'s inspection, health probe, last deploy and log tail, which is what makes it reproducible. The account name itself is never transmitted: it travels as a salted hash. Example: shop. Sent to the API as `project`.')->required(),
            'contact' => $schema->string()->description('An address support can answer on. Optional, sent unredacted, and the only personal data in the report — supply it only with the reporter\'s knowledge. Example: ops@example.com.'),
            'attach_log' => $schema->boolean()->description('Attach the tail of the project\'s deploy log. Ignored when the install runs below telemetry tier 2.'),
            'attach_health' => $schema->boolean()->description('Probe the application\'s published ports while filing. Costs a few seconds and touches the account container; turn it off to file without waiting, or for a project that is deliberately stopped.'),
        ];
    }
}
