<?php
/*
 * CouchCMS installation, driven from the deploy instead of from a visitor.
 *
 * couch/install.php is a web installer with no gate on it: header.php looks
 * for the `k_couch_version` row, does not find it, and hands the request to a
 * form that creates every table and the super-admin account from whatever it
 * is posted. On a public URL that is first-visitor-wins -- the same hole found
 * in Koillection, Outline, NocoDB and Mattermost. The window has to be closed
 * before Apache binds, and the only way to close it is to be the first
 * visitor.
 *
 * So this runs CouchCMS's own installer in a CLI process from the install
 * stage, with a password generated per account, and never over the network. No
 * `php -S`, no curl, no temporary listening socket: the request is assembled in
 * $_SERVER and $_POST and header.php is included exactly as couch/index.php
 * would include it. Upstream's schema, upstream's password hashing, upstream's
 * validation -- nothing here reimplements any of it.
 *
 * Modes:
 *   config   write couch/config.php from couch/config.example.php, filling in
 *            the database the engine provisioned and the account's own URL.
 *   check    print `installed=0|1 template=0|1` and exit 0. Reads the database
 *            directly with mysqli, so it works before CouchCMS is installed.
 *   install  run the installer once. Prints upstream's own HTML; the caller
 *            greps it.
 *   render   request `/` as the super-admin. This is what registers the
 *            starter template and creates its master page -- CouchCMS only
 *            does that for a logged-in super-admin, so a visitor arriving at an
 *            unregistered template is bounced to the login screen. It also
 *            gives header.php the chance to run couch/upgrade.php, which is how
 *            CouchCMS migrates its schema, from the deploy rather than from
 *            whoever happens to request the site after a version bump.
 */

if ( PHP_SAPI !== 'cli' ) {
    // Belt and braces: Apache is told to deny `panelalpha-*` in the generated
    // vhost, and this file is only reachable at all because CouchCMS is served
    // from the project root.
    header( 'HTTP/1.1 403 Forbidden' );
    die( 'Forbidden' );
}

// Anything PHP has to say goes to stderr. `check` prints shell assignments
// that the caller eval's, and a warning or a fatal on stdout would be eval'd
// with them -- an error message containing an apostrophe is an unterminated
// string in the calling shell rather than a readable failure.
ini_set( 'display_errors', 'stderr' );

$mode  = isset( $argv[1] ) ? $argv[1] : '';
$root  = '/app';
$couch = $root . '/couch/';

// The account's public address, as the engine passes it. PublicUrlEnvironment
// sets APP_URL, URL, SITE_URL and the rest to the same value.
$url   = getenv( 'APP_URL' ) ?: ( getenv( 'URL' ) ?: '' );
$host  = parse_url( $url, PHP_URL_HOST ) ?: 'localhost';
$https = stripos( $url, 'https://' ) === 0;

$user  = getenv( 'COUCH_ADMIN_USER' ) ?: 'admin';
$email = getenv( 'COUCH_ADMIN_EMAIL' ) ?: ( 'admin@' . $host );

function couch_fail( $msg ) {
    fwrite( STDERR, "[couchcms] {$msg}\n" );
    exit( 1 );
}

/* ----------------------------------------------------------------- config */

if ( $mode === 'config' ) {
    $example = $couch . 'config.example.php';
    $target  = $couch . 'config.php';

    $src = @file_get_contents( $example );
    if ( $src === false ) {
        couch_fail( "cannot read {$example}" );
    }

    foreach ( array( 'DB_HOST', 'DB_DATABASE', 'DB_USERNAME' ) as $required ) {
        if ( getenv( $required ) === false || getenv( $required ) === '' ) {
            couch_fail( "{$required} is not in the environment; is `database: mysql` still in panelalpha.yaml?" );
        }
    }

    // mysql2i's mysql_connect() splits the host on ':' and passes the second
    // half to mysqli_connect() as the port. The port is always appended rather
    // than only when it is non-standard, because the shim reads $db_host[1]
    // and strlen()s it unconditionally -- on PHP 8 a host without a colon is an
    // "Undefined array key 1" warning on every single request.
    $db_host = getenv( 'DB_HOST' ) . ':' . ( getenv( 'DB_PORT' ) ?: '3306' );

    // K_SITE_URL must end in a slash -- config.example.php says so in capitals,
    // and K_ADMIN_URL is built by concatenating 'couch/' onto it.
    $site_url = rtrim( $url, '/' ) . '/';

    // Single-quoted PHP strings: a backslash and a quote are the only two
    // characters that mean anything. The database password is generated by the
    // engine and nothing promises it holds neither.
    $q = function ( $value ) {
        return "'" . str_replace( array( '\\', "'" ), array( '\\\\', "\\'" ), $value ) . "'";
    };

    $edits = array(
        // Commented out in the example, and this is the value the comment above
        // it calls M.IMP: without it CouchCMS guesses its own address from
        // DOCUMENT_ROOT and the Host header of whoever is asking.
        "/^\\s*\\/\\/define\\(\\s*'K_SITE_URL'.*$/m"
            => "    define( 'K_SITE_URL', " . $q( $site_url ) . " );",
        "/^\\s*define\\(\\s*'K_DB_NAME'.*$/m"
            => "    define( 'K_DB_NAME', " . $q( getenv( 'DB_DATABASE' ) ) . " );",
        "/^\\s*define\\(\\s*'K_DB_USER'.*$/m"
            => "    define( 'K_DB_USER', " . $q( getenv( 'DB_USERNAME' ) ) . " );",
        "/^\\s*define\\(\\s*'K_DB_PASSWORD'.*$/m"
            => "    define( 'K_DB_PASSWORD', " . $q( (string) getenv( 'DB_PASSWORD' ) ) . " );",
        "/^\\s*define\\(\\s*'K_DB_HOST'.*$/m"
            => "    define( 'K_DB_HOST', " . $q( $db_host ) . " );",
        // The container's clock is UTC; the example ships +5.5 (India).
        "/^\\s*define\\(\\s*'K_GMT_OFFSET'.*$/m"
            => "    define( 'K_GMT_OFFSET', 0 );",
        // Contact-form addresses. The example ships someone's gmail account.
        "/^\\s*define\\(\\s*'K_EMAIL_TO'.*$/m"
            => "    define( 'K_EMAIL_TO', " . $q( $email ) . " );",
        "/^\\s*define\\(\\s*'K_EMAIL_FROM'.*$/m"
            => "    define( 'K_EMAIL_FROM', " . $q( 'noreply@' . $host ) . " );",
    );

    if ( $https ) {
        // Section 1.1: has to be uncommented when K_SITE_URL is https, or
        // CouchCMS builds http:// links and its login cookie is not marked
        // secure.
        $edits["/^\\s*\\/\\/define\\(\\s*'K_HTTPS'.*$/m"] = "    define( 'K_HTTPS', '1' );";
    }

    foreach ( $edits as $pattern => $replacement ) {
        $count = 0;
        // The replacement is a literal: a database password containing `$1`
        // would otherwise be read as a backreference.
        $src = preg_replace_callback(
            $pattern,
            function () use ( $replacement ) { return $replacement; },
            $src,
            1,
            $count
        );
        if ( $count !== 1 ) {
            couch_fail( "config.example.php no longer contains {$pattern} -- upstream changed it" );
        }
    }

    // Sections 99 and 100 of config.example.php are left exactly as upstream
    // ships them: K_PAID_LICENSE 0 and K_REMOVE_FOOTER_LINK 0. CouchCMS is
    // under the Common Public Attribution License, whose Exhibit B requires the
    // Original Developer's attribution to be displayed whenever the software is
    // run, and those two constants are the mechanism. Turning either on without
    // a commercial licence is a licence violation, and it is not PanelAlpha's
    // to turn on for a customer. See README.md beside this file.

    if ( file_put_contents( $target, $src ) === false ) {
        couch_fail( "cannot write {$target}" );
    }
    // It holds the database password. It is not web-readable -- it dies when
    // requested directly, because K_COUCH_DIR is not defined -- but it is the
    // account's secret and the mode should say so.
    chmod( $target, 0600 );

    echo "[couchcms] wrote couch/config.php for " . getenv( 'DB_DATABASE' ) . '@' . getenv( 'DB_HOST' ) . "\n";
    exit( 0 );
}

/* ------------------------------------------------------------------ check */

if ( $mode === 'check' ) {
    // PHP 8.1 turned mysqli's error mode into exceptions by default, and `@`
    // does not suppress an exception. Both queries below are asked before
    // CouchCMS is installed, when the tables genuinely do not exist, so a
    // missing table has to come back as a false rather than as a fatal error
    // whose message would be the only thing on stdout.
    mysqli_report( MYSQLI_REPORT_OFF );

    $port = getenv( 'DB_PORT' ) ?: '3306';
    $db = @new mysqli(
        getenv( 'DB_HOST' ),
        getenv( 'DB_USERNAME' ),
        getenv( 'DB_PASSWORD' ),
        getenv( 'DB_DATABASE' ),
        (int) $port
    );
    if ( $db->connect_errno ) {
        couch_fail( 'cannot reach the database: ' . $db->connect_error );
    }

    $installed = 0;
    $template  = 0;

    // A missing table is an error rather than an empty result, so both queries
    // are allowed to fail: before the installer runs, neither table exists.
    $rs = @$db->query( "SELECT k_value FROM couch_settings WHERE k_key='k_couch_version'" );
    if ( $rs && $rs->num_rows > 0 ) {
        $installed = 1;
    }

    $rs = @$db->query( "SELECT id FROM couch_templates WHERE name='index.php' AND deleted='0'" );
    if ( $rs && $rs->num_rows > 0 ) {
        $template = 1;
    }

    // One assignment per line: the caller filters this through a grep that
    // anchors both ends, so a second assignment on the same line would be
    // dropped with it.
    echo "installed={$installed}\ntemplate={$template}\n";
    exit( 0 );
}

/* --------------------------------------------------------- shared request */

// What Apache would have put in $_SERVER. CouchCMS reads DOCUMENT_ROOT and
// SCRIPT_NAME to work out where it is mounted, SERVER_SOFTWARE to refuse IIS,
// and HTTP_HOST for its cookie domain.
$_SERVER['REQUEST_METHOD']  = 'GET';
$_SERVER['SERVER_SOFTWARE'] = 'Apache';
$_SERVER['SERVER_PROTOCOL'] = 'HTTP/1.1';
$_SERVER['HTTP_HOST']       = $host;
$_SERVER['SERVER_NAME']     = $host;
$_SERVER['SERVER_PORT']     = $https ? '443' : '80';
$_SERVER['REMOTE_ADDR']     = '127.0.0.1';
$_SERVER['DOCUMENT_ROOT']   = $root;
$_SERVER['HTTP_USER_AGENT'] = 'PanelAlpha deploy';
if ( $https ) {
    $_SERVER['HTTPS'] = 'on';
}

if ( ! is_file( $couch . 'config.php' ) ) {
    couch_fail( 'couch/config.php does not exist yet -- panelalpha-setup.sh writes it' );
}

/* ---------------------------------------------------------------- install */

if ( $mode === 'install' ) {
    $pwd_file = $root . '/.panelalpha-admin-password';
    if ( ! is_file( $pwd_file ) ) {
        couch_fail( "{$pwd_file} is missing; hooks/prepare.sh generates it" );
    }
    $pwd = trim( file_get_contents( $pwd_file ) );
    if ( strlen( $pwd ) < 5 ) {
        couch_fail( 'the generated admin password is too short for CouchCMS (min 5)' );
    }

    // The installer is couch/install.php, included by header.php when the
    // version row is missing, and it processes an ordinary form post. The
    // hidden field is what <cms:form> uses to decide a form was submitted;
    // there is no CSRF nonce on this one, because a nonce is only added to
    // forms bound to a page and the install form is not.
    $_SERVER['REQUEST_METHOD']  = 'POST';
    $_SERVER['SCRIPT_NAME']     = '/couch/index.php';
    $_SERVER['PHP_SELF']        = '/couch/index.php';
    $_SERVER['REQUEST_URI']     = '/couch/index.php';
    $_SERVER['SCRIPT_FILENAME'] = $couch . 'index.php';

    $_POST = array(
        'k_hid_frm_login'  => 'frm_login',
        'name'             => $user,
        'email'            => $email,
        'password'         => $pwd,
        'repeat_password'  => $pwd,
        'k_install'        => 'Install',
    );
    $_REQUEST = $_POST;

    chdir( $couch );
    define( 'K_ADMIN', 1 );
    define( 'K_COUCH_DIR', $couch );

    // install.php ends in die(), so this never returns. The caller reads the
    // HTML for "Installation successful" and re-runs `check`.
    require $couch . 'header.php';
    exit( 0 );
}

/* ----------------------------------------------------------------- render */

if ( $mode === 'render' ) {
    $_SERVER['SCRIPT_NAME']     = '/index.php';
    $_SERVER['PHP_SELF']        = '/index.php';
    $_SERVER['REQUEST_URI']     = '/';
    $_SERVER['SCRIPT_FILENAME'] = $root . '/index.php';

    chdir( $root );
    define( 'K_COUCH_DIR', $couch );

    // header.php runs couch/upgrade.php here if the schema is older than the
    // checkout, then builds $AUTH for an anonymous visitor.
    require $couch . 'header.php';

    // Become the super-admin for this one process. CouchCMS's own check is
    // `$AUTH->user->access_level >= K_ACCESS_LEVEL_SUPER_ADMIN`, and KUser
    // loads the account by name out of the database -- no cookie to forge and
    // no password to re-verify, because this is a CLI process running as the
    // account that owns the files.
    $AUTH->user = new KUser( $user );
    if ( $AUTH->user->id == -1 ) {
        couch_fail( "no such CouchCMS user: {$user}" );
    }
    if ( $AUTH->user->access_level < K_ACCESS_LEVEL_SUPER_ADMIN ) {
        couch_fail( "{$user} is not a super-admin; refusing to register the template" );
    }

    // index.php is an ordinary CouchCMS template: it requires couch/cms.php
    // (already loaded, so require_once is a no-op) and calls COUCH::invoke(),
    // which is what inserts the couch_templates row and the master page.
    // The rendered page goes to stdout and lands in the deploy log.
    require $root . '/index.php';

    // The master page CouchCMS creates for a template it has just met is
    // titled "Default page for index.php * PLEASE CHANGE THIS TITLE *", which
    // is fine advice for a developer and not something to publish as the
    // heading of somebody's home page. Guarded on that exact prefix, so a
    // redeploy never touches a title the account has since edited.
    $rs = $DB->select( K_TBL_TEMPLATES, array( 'id' ), "name='index.php'" );
    if ( count( $rs ) ) {
        $DB->update(
            K_TBL_PAGES,
            array( 'page_title' => 'Home' ),
            "template_id='" . $DB->sanitize( $rs[0]['id'] ) . "' AND is_master='1'"
                . " AND page_title LIKE 'Default page for%'"
        );
    }

    exit( 0 );
}

couch_fail( "unknown mode '{$mode}' (check|install|render)" );
