<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Git;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('git_connect')]
#[Description(<<<'MARKDOWN'
    Connect a directory to a git remote

    Connect a directory to a git remote. Optional `path` defaults to `project` on DinD and `public_html` on FPM/LiteSpeed. Body `repo_url` and `branch` are required. Optional `token` is a PAT (never logged). Set `repair` to re-adopt a missing .git. On a `deploy` account without repair this only keeps origin in sync and persists metadata — it does not clone from scratch.
    MARKDOWN)]
#[IsDestructive]
class GitConnectTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/git/connect';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'path',
            'repo_url',
            'branch',
            'token',
            'auth_type',
            'repair',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'path' => $schema->string()->description('Optional. Defaults to `project` (DinD) or `public_html` (FPM/LiteSpeed).'),
            'repo_url' => $schema->string()->required(),
            'branch' => $schema->string()->required(),
            'token' => $schema->string(),
            'auth_type' => $schema->string()->description('One of: pat.'),
            'repair' => $schema->boolean(),
        ];
    }
}
