<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Git;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('git_deploy_hook_show')]
#[Description(<<<'MARKDOWN'
    Show a push-to-deploy hook

    Show the Deploy Hook of a checkout: its `url` and when it was created or last rotated. Never includes the secret, which is shown only when the hook is created or rotated. `registered_url` is the address this hook was last created or rotated under; `url_changed_since_registration` is true once the engine's own address has moved on from it (an IP a domain certificate replaced), meaning the git host still calls `registered_url` and the hook has to be re-registered at `url`. `tls` reports the same certificate state POST .../deploy-hook does. `deliveries` lists the 20 most recent accepted Hook Deliveries and the 5 most recent rejected ones, newest first: `outcome` is what the request was answered with (queued, ignored, rejected, coalesced) and `result` is what the queued work then reached (deployed, partial, deploy_failed, pull_refused, superseded), null while still queued or for a delivery that queued nothing. `detail` carries the reason for a refused pull or a failure; `deploy_id` points at the full build log (`php artisan project:deploy:log <project> --id=<deploy_id>`) for a delivery that started one. Optional `path` defaults to `project` on DinD and `public_html` on FPM/LiteSpeed. 404 when the checkout has no hook.

    Calls GET /api/projects/{username}/git/deploy-hook.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class GitDeployHookShowTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/projects/{username}/git/deploy-hook';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function queryParams(): array
    {
        return [
            'path',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('Name of the project. Sent to the API as `username`.')->required(),
            'path' => $schema->string()->description('Optional. Defaults to `project` (DinD) or `public_html` (FPM/LiteSpeed).'),
        ];
    }
}
