<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Git;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('git_deploy_hook_create')]
#[Description(<<<'MARKDOWN'
    Create a push-to-deploy hook

    Create the Deploy Hook for a git-connected checkout, so a push to its tracked branch redeploys the project. Optional `path` defaults to `project` on DinD and `public_html` on FPM/LiteSpeed (`project` is the Deploy-managed checkout). Returns the `url` to register in the git host and the `secret` to sign with. The secret is shown ONCE, in this response, and can never be read again: store it now, or rotate later. Asking again returns the same hook (200) without the secret and never rotates it. On the Deploy-managed checkout every push to the tracked branch force-updates it to match the repository (local changes to tracked files and untracked files that are not engine-managed are discarded before the rebuild) and the response carries a `warning` saying so. On a Site Git checkout (e.g. `public_html`) a push only fast-forwards, with no build: untracked files such as uploads are left alone, and when git refuses because of a local change, an untracked file at an incoming path or rewritten history, nothing changes and the delivery's result is `pull_refused`. The response's `tls` block says whether the engine's certificate is one a git host trusts outright (`state: valid`) or self-signed (`state: self_signed`); when self-signed it carries `instructions`, one paragraph per supported provider (github, gitlab, bitbucket-cloud, bitbucket-data-center) on making that provider call the hook anyway. Optional `provider` on the request narrows `instructions` to that one provider. `tls.warning` is set when the engine has no public address, so a git host on the internet could not reach the hook at all. 422 when the checkout is not connected to git.

    Calls POST /api/projects/{username}/git/deploy-hook. This changes server state.
    MARKDOWN)]
#[IsDestructive]
class GitDeployHookCreateTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/git/deploy-hook';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'path',
            'provider',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('Name of the project. Sent to the API as `username`.')->required(),
            'path' => $schema->string()->description('Optional. Defaults to `project` (DinD) or `public_html` (FPM/LiteSpeed).'),
            'provider' => $schema->string()->description('Optional. Narrows `tls.instructions` to this git host: github, gitlab, bitbucket-cloud, bitbucket-data-center.'),
        ];
    }
}
