<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Git;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('git_deploy_key_create')]
#[Description(<<<'MARKDOWN'
    Create a git deploy key

    Create the project's SSH deploy key, or return the one it has: `public_key` is the line to add to the repository as a read-only deploy key, then connect an SSH remote with git_connect. The private key is stored encrypted and never returned. Host keys are pinned: github.com, gitlab.com and bitbucket.org from their published keys; for another host pass `host` (`git.example.com` or `git.example.com:2222`) and its keys are read once and pinned, with their `fingerprints` returned to check. 201 when the key was created, 200 when it existed; never rotates (delete and create again for a new key).
    MARKDOWN)]
#[IsDestructive]
class GitDeployKeyCreateTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/git/deploy-key';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'host',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'host' => $schema->string()->description('Optional. A git host other than github.com, gitlab.com or bitbucket.org to pin, with an optional :port.'),
        ];
    }
}
