<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Git;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;

#[Name('git_deploy_key_delete')]
#[Description(<<<'MARKDOWN'
    Delete a git deploy key

    Delete the project's SSH deploy key and the host keys pinned with it. SSH remotes stop authenticating; remove the key from the repository too. 404 when the project has no deploy key.
    MARKDOWN)]
#[IsDestructive]
#[IsIdempotent]
class GitDeployKeyDeleteTool extends ApiTool
{
    protected function method(): string
    {
        return 'DELETE';
    }

    protected function path(): string
    {
        return '/projects/{username}/git/deploy-key';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
        ];
    }
}
