<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Git;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('git_pull')]
#[Description(<<<'MARKDOWN'
    Pull from the git remote

    Pull from the git remote. Optional `path` defaults to `project` on DinD and `public_html` on FPM/LiteSpeed. Body `strategy` is `ff` (default), `force` (`reset --hard` origin/<branch> plus clean -fd), or `push_first`. `ff` fetches and fast-forwards, and git alone decides whether the checkout allows it: untracked files (uploads, caches) and edits to files the incoming commits leave alone do not block it. It returns 422 naming the paths when a local edit or untracked file sits where an incoming commit writes, or 422 when history has diverged (for example after a force-push); the checkout is left as it was. On a Deploy-managed checkout (`managed_by` is `deploy`) a successful pull rebuilds the app from the pulled files. Confirm with the operator before `force`.

    Calls POST /api/projects/{username}/git/pull. This changes server state.
    MARKDOWN)]
#[IsDestructive]
class GitPullTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/git/pull';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'path',
            'strategy',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('Name of the project. Sent to the API as `username`.')->required(),
            'path' => $schema->string()->description('Optional. Defaults to `project` (DinD) or `public_html` (FPM/LiteSpeed).'),
            'strategy' => $schema->string()->description('One of: ff, force, push_first.'),
        ];
    }
}
