<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Git;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('git_pull')]
#[Description(<<<'MARKDOWN'
    Pull from the git remote

    Pulls the connected branch. Optional `path` defaults to `project` on DinD and the document root of the main domain on FPM/LiteSpeed. `strategy`: `ff` (default) fast-forwards and is refused when history has diverged or a local edit or untracked file sits where an incoming commit writes; `force` is `reset --hard` to origin plus clean -fd; `push_first` pushes local commits first. Confirm with the operator before `force`. On a managed_by deploy checkout the change and the rebuild after it run in the background: the answer is a task `id` at once; follow it with task_get until completed, failed or cancelled (a failure is in details.error and details.problems, the deployed commit in details.commit). A 409 means a deploy is already running: follow the task_id it names with task_get (task_cancel if it is stuck), or deploy_log_get when task_id is null, instead of calling again.
    MARKDOWN)]
#[IsDestructive]
class GitPullTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/git/pull';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'path',
            'strategy',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'path' => $schema->string()->description('Optional. Defaults to `project` (DinD) or the document root of the main domain (FPM/LiteSpeed).'),
            'strategy' => $schema->string()->description('One of: ff, force, push_first.'),
        ];
    }
}
