<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Git;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('git_push')]
#[Description(<<<'MARKDOWN'
    Push local git changes

    Push local git changes. Optional `path` defaults to `project` on DinD and `public_html` on FPM/LiteSpeed. If the working tree is dirty this tool will commit all changes itself, then push. Returns 422 `Pull first.` when behind the remote, or when managed_by is `deploy`.
    MARKDOWN)]
#[IsDestructive]
class GitPushTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/git/push';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'path',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'path' => $schema->string()->description('Optional. Defaults to `project` (DinD) or `public_html` (FPM/LiteSpeed).'),
        ];
    }
}
