<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Git;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('git_status')]
#[Description(<<<'MARKDOWN'
    Git repository status

    Call this first. Optional `path` defaults to `project` on DinD and the document root of the main domain on FPM/LiteSpeed. Query `fetch` updates remote-tracking refs before reporting. The payload includes `managed_by`: `deploy` (account provisioned with git_repo; mutating Git must go through `project_rebuild`) or `site_git` (these Git tools). `connecting: true` means a connect is still fetching the repository: wait and poll; do not call connect again.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class GitStatusTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/projects/{username}/git/status';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function queryParams(): array
    {
        return [
            'path',
            'fetch',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'path' => $schema->string()->description('Optional. Defaults to `project` (DinD) or the document root of the main domain (FPM/LiteSpeed).'),
            'fetch' => $schema->boolean(),
        ];
    }
}
