<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Git;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;

#[Name('git_update_credentials')]
#[Description(<<<'MARKDOWN'
    Update git credentials for a directory

    Update git credentials for a directory. Optional `path` defaults to `project` on DinD and `public_html` on FPM/LiteSpeed. Sending `token` (including empty) updates stored credentials. Omitting `token` is a no-op that returns status.
    MARKDOWN)]
#[IsDestructive]
#[IsIdempotent]
class GitUpdateCredentialsTool extends ApiTool
{
    protected function method(): string
    {
        return 'PUT';
    }

    protected function path(): string
    {
        return '/projects/{username}/git/update-credentials';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'path',
            'token',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'path' => $schema->string()->description('Optional. Defaults to `project` (DinD) or `public_html` (FPM/LiteSpeed).'),
            'token' => $schema->string(),
        ];
    }
}
