<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\System;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;

#[Name('system_ssl_config_set')]
#[Description(<<<'MARKDOWN'
    Set how certificates for project sites are obtained

    Only the fields present are changed. `issuer` self_signed (the default) means the engine signs each project domain's certificate itself; acme means it obtains one from an authority over HTTP-01 as each domain is created, which needs the domain to resolve to this host. `sites_base_domain` is what a project without a domain of its own is named under: <project>.<that>.
    MARKDOWN)]
#[IsDestructive]
#[IsIdempotent]
class SystemSslConfigSetTool extends ApiTool
{
    protected function method(): string
    {
        return 'PUT';
    }

    protected function path(): string
    {
        return '/system/ssl-config';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'issuer',
            'sites_base_domain',
            'acme_directory_url',
            'acme_email',
            'shared_zone_issuance',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'issuer' => $schema->string()->description('One of: self_signed, acme.'),
            'sites_base_domain' => $schema->string()->description('The domain new projects are named under. Empty clears it. A wildcard zone the fleet shares is accepted and reported as shared_zone: certificates there spend an allowance every engine on it draws on.'),
            'acme_directory_url' => $schema->string()->description('Any RFC 8555 directory URL. \'staging\' and \'live\' are shorthands for Let\'s Encrypt\'s. Empty restores the default.'),
            'acme_email' => $schema->string()->description('ACME account contact; empty clears it.'),
            'shared_zone_issuance' => $schema->boolean()->description('Whether to obtain certificates for names on a wildcard zone the whole fleet shares (panelalpha.direct, nip.io, sslip.io). Off by default: those are one registered domain each for every engine, and Let\'s Encrypt counts 50 new certificates per registered domain per week across all of them. On, a project on the default name gets a real certificate like any other; off, it keeps the self-signed one and the reason is logged. Domains a customer owns are never affected either way.'),
        ];
    }
}
