<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\System;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;

#[Name('system_engine_cert_request')]
#[Description(<<<'MARKDOWN'
    Request the engine's own Let's Encrypt certificate

    Obtains the certificate :2011 serves, for `domain` or the cert_domain setting. **This briefly takes every hosted site offline**: certbot needs the host's :80 and sites-http holds it, so the webserver is stopped for the length of the challenge and brought back after — usually seconds. It is not the mechanism project certificates use. Blocks until the request finishes, up to 15 minutes. Use dry_run first: it runs the full challenge against staging and writes nothing.
    MARKDOWN)]
#[IsDestructive]
#[IsIdempotent]
class SystemEngineCertRequestTool extends ApiTool
{
    protected function method(): string
    {
        return 'PUT';
    }

    protected function path(): string
    {
        return '/system/engine-certificate';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'domain',
            'email',
            'ip',
            'staging',
            'force_renewal',
            'skip_dns_check',
            'dry_run',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'domain' => $schema->string()->description('The name to certify; default: the cert_domain setting.'),
            'email' => $schema->string()->description('ACME account email; default: the cert_email setting.'),
            'ip' => $schema->string()->description('The public address, when detection gets it wrong.'),
            'staging' => $schema->boolean()->description('Let\'s Encrypt staging: untrusted, spends no rate limit.'),
            'force_renewal' => $schema->boolean(),
            'skip_dns_check' => $schema->boolean()->description('Do not verify the name resolves to this host first.'),
            'dry_run' => $schema->boolean()->description('Full challenge, no certificate, nothing installed.'),
        ];
    }
}
