<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\System;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;

#[Name('system_update')]
#[Description(<<<'MARKDOWN'
    Trigger a system update
    MARKDOWN)]
#[IsDestructive]
#[IsIdempotent]
class SystemUpdateTool extends ApiTool
{
    protected function method(): string
    {
        return 'PUT';
    }

    protected function path(): string
    {
        return '/system/update';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'license_key',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'license_key' => $schema->string(),
        ];
    }
}
