<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\ModSecurity;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;

#[Name('modsec_custom_rules_set')]
#[Description(<<<'MARKDOWN'
    Replace the custom ModSecurity rules

    The rules go live only after the webserver config test parses them with every enabled ruleset, and, when they are loaded, passes the live config with them in place; otherwise the call answers 422 with what the test said and the live rules stay as they were. On nginx the test also runs them, and refuses rules that would switch ModSecurity off or to detection-only, stop the rules around them or the reading of request bodies, or deny an ordinary request; SecRuleEngine and ctl:ruleEngine are refused anywhere in the rules, skip is refused, and a skipAfter must name a SecMarker after it. An operator ModSecurity does not know is refused too, since ModSecurity would read it as a regular expression. Rule ids must be in 1100000-1199999. They apply once the `custom` ruleset is enabled and the mode is not off.
    MARKDOWN)]
#[IsDestructive]
#[IsIdempotent]
class ModsecCustomRulesSetTool extends ApiTool
{
    protected function method(): string
    {
        return 'PUT';
    }

    protected function path(): string
    {
        return '/modsec/custom-rules';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'rules',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'rules' => $schema->string()->description('The whole rule file: SecRule, SecAction, SecMarker and SecRuleRemove/Update directives. Empty clears it. Example: SecRule REQUEST_URI "@beginsWith /xyz" "id:1100001,phase:1,deny,status:403,log".')->required(),
        ];
    }
}
