<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\ModSecurity;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('modsec_audit_log_tail')]
#[Description(<<<'MARKDOWN'
    Tail a ModSecurity audit log file
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class ModsecAuditLogTailTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/modsec/audit-log/files/{filename}/tail';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'filename',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'filename' => $schema->string()->required(),
        ];
    }
}
