<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Deploy;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('deploy_log_get')]
#[Description(<<<'MARKDOWN'
    Poll the deploy log (JSON-lines) from a byte-like line offset

    A page of the latest deploy log from `offset`. While `more` is true, call again with `next_offset`. `problem` carries the fix when a failed deploy is a known failure.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class DeployLogGetTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/projects/{username}/deploy-log';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function queryParams(): array
    {
        return [
            'offset',
            'max_bytes',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function defaults(): array
    {
        return [
            'max_bytes' => '49152',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->required(),
            'offset' => $schema->integer(),
            'max_bytes' => $schema->integer()->min(1024)->description('Page size in bytes, at least 1024. This tool sends 49152 when it is omitted.'),
        ];
    }
}
