<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Deploy;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('deploy_log_get')]
#[Description(<<<'MARKDOWN'
    Poll the deploy log (JSON-lines) from a byte-like line offset

    Returns a page of lines from `offset`. While `more` is true there are lines after this page: ask again with `offset` set to `next_offset`. `max_bytes` bounds a page by size as well as by line count.

    When the latest deploy failed and PanelAlpha monitoring knows how to fix that failure, `problem` carries the fix (title, body_why, body_fix, fixed_in_version, ...); otherwise it is null.

    Calls GET /api/projects/{username}/deploy-log.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class DeployLogGetTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/projects/{username}/deploy-log';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function queryParams(): array
    {
        return [
            'offset',
            'max_bytes',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function defaults(): array
    {
        return [
            'max_bytes' => '49152',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('Name of the project. Sent to the API as `username`.')->required(),
            'offset' => $schema->integer(),
            'max_bytes' => $schema->integer()->description('Upper bound on the log text in one page, at least 1024. Omitted: up to 2000 lines, whatever their size. This tool sends 49152 when it is omitted.'),
        ];
    }
}
