<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Deploy;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('source_inspect')]
#[Description(<<<'MARKDOWN'
    Inspect an application source and report its stack, ports and services

    Detects what an application is without deploying it. The source may be a Git repository URL, an absolute path on this server, or the username of an existing project (its files under the account home directory). Git sources are cloned shallow into a temporary directory and removed again. Values from .env files are never returned - only the variable names. A project username returns the same report as GET /projects/{username}/inspect, including the `deployment` snapshot its last deploy froze and the `drift` between that and the files on disk - so a caller that already has a username does not need the other endpoint.

    Calls POST /api/source/inspect.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class SourceInspectTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/source/inspect';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'source',
            'type',
            'branch',
            'subdirectory',
            'git_token',
            'recipe',
            'stages',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'source' => $schema->string()->description('Repository URL (the scheme may be left out), absolute path, or project username. Example: github.com/owner/repo.')->required(),
            'type' => $schema->string()->description('How to read `source`. Detected from its shape when omitted. One of: git, path, project.'),
            'branch' => $schema->string()->description('Git branch to inspect.'),
            'subdirectory' => $schema->string()->description('Inspect this directory inside the source instead of its root. For a project the source root is the account home directory, so this is a path under /home/<username> such as "project/apps/api" or "public_html".'),
            'git_token' => $schema->string()->description('Access token for a private HTTPS repository. A `vault:<id>` of a `global` vault entry is accepted here in place of the literal token. A `project` entry is accepted while no project owns it yet, and inspecting does not assign it; one a project owns is refused. Omitted, the clone is anonymous.'),
            'recipe' => $schema->string()->description('Preview the deploy this recipe would produce instead of the one detection picks. Takes an id from `application.candidates` in a previous inspection, and is the same field the deploy endpoints accept - so what this previews is what deploying with it executes. An id this engine does not ship comes back as `application.issue` rather than an error. Example: php.'),
            'stages' => $schema->object()->description('Preview a deploy that overrides stages: the same `stages` payload the deploy endpoints take, reported here without deploying anything. A stage named replaces that stage in the returned plan; one left out keeps the platform defaults. Each command in `application.stages` says where it came from in `source`: manifest, app_config or request.'),
        ];
    }
}
