<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\ProxyRules;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;

#[Name('proxy_rule_update')]
#[Description(<<<'MARKDOWN'
    Update a proxy rule

    Update a proxy rule.
    MARKDOWN)]
#[IsDestructive]
#[IsIdempotent]
class ProxyRuleUpdateTool extends ApiTool
{
    protected function method(): string
    {
        return 'PUT';
    }

    protected function path(): string
    {
        return '/proxy-rules/{id}';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'id',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'upstream_host',
            'upstream_port',
            'upstream_protocol',
            'enabled',
            'metadata',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'id' => $schema->integer()->required(),
            'upstream_host' => $schema->string(),
            'upstream_port' => $schema->integer(),
            'upstream_protocol' => $schema->string(),
            'enabled' => $schema->boolean(),
            'metadata' => $schema->object(),
        ];
    }
}
