<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\ProxyRules;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('proxy_rule_create')]
#[Description(<<<'MARKDOWN'
    Create a proxy rule

    Create a new proxy rule.
    MARKDOWN)]
#[IsDestructive]
class ProxyRuleCreateTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/proxy-rules';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'owner_scope',
            'username',
            'transport',
            'listen_ip',
            'listen_port',
            'server_name',
            'upstream_host',
            'upstream_port',
            'upstream_protocol',
            'enabled',
            'metadata',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'owner_scope' => $schema->string()->description('Who owns the rule. Defaults to user. One of: system, user.'),
            'name' => $schema->string()->description('Project the rule belongs to. Required when owner_scope is user.'),
            'transport' => $schema->string()->description('One of: http, tcp, udp.')->required(),
            'listen_ip' => $schema->string(),
            'listen_port' => $schema->integer()->required(),
            'server_name' => $schema->string(),
            'upstream_host' => $schema->string()->description('Example: 127.0.0.1.')->required(),
            'upstream_port' => $schema->integer()->required(),
            'upstream_protocol' => $schema->string(),
            'enabled' => $schema->boolean(),
            'metadata' => $schema->object(),
        ];
    }
}
