<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\CSF;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;

#[Name('csf_disable')]
#[Description(<<<'MARKDOWN'
    Disable CSF firewall

    csf -x does real iptables/lfd teardown and can run past a typical client timeout, so this returns as soon as the disable is queued rather than waiting for it to finish. Poll GET /csf/status for enabled:false to confirm.
    MARKDOWN)]
#[IsDestructive]
#[IsIdempotent]
class CsfDisableTool extends ApiTool
{
    protected function method(): string
    {
        return 'PUT';
    }

    protected function path(): string
    {
        return '/csf/disable';
    }



    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [];
    }
}
