<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\CSF;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;

#[Name('csf_rule_update')]
#[Description(<<<'MARKDOWN'
    Edit a CSF firewall rule

    A field not sent keeps its current value; send null to clear it.
    MARKDOWN)]
#[IsDestructive]
#[IsIdempotent]
class CsfRuleUpdateTool extends ApiTool
{
    protected function method(): string
    {
        return 'PUT';
    }

    protected function path(): string
    {
        return '/csf/rules/{type}/{lineMd5}';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'type',
            'lineMd5',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'target',
            'comment',
            'protocol',
            'direction',
            'port_prefix',
            'port',
            'target_prefix',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'type' => $schema->string()->description('One of: allow, deny.')->required(),
            'lineMd5' => $schema->string()->required(),
            'target' => $schema->string()->description('An IPv4 or IPv6 address or CIDR range, or a numeric uid when target_prefix is u=.')->required(),
            'comment' => $schema->string(),
            'protocol' => $schema->string()->description('A port rule, e.g. tcp|in|d=22|s=1.2.3.4, takes protocol, direction, port_prefix, port and target_prefix together, and a partial set is refused. Leave all five out for a rule on the bare target. One of: tcp, udp.'),
            'direction' => $schema->string()->description('One of: in, out.'),
            'port_prefix' => $schema->string()->description('Source or destination port. One of: s=, d=.'),
            'port' => $schema->string()->description('Example: 22.'),
            'target_prefix' => $schema->string()->description('Source or destination address, or a user id. One of: s=, d=, u=.'),
        ];
    }
}
