<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Lighthouse;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('lighthouse_report_create')]
#[Description(<<<'MARKDOWN'
    Generate a Lighthouse performance report
    MARKDOWN)]
#[IsDestructive]
class LighthouseReportCreateTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/lighthouse/generate-report';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'url',
            'desktop_preset',
            'no_local_resolve',
            'strip_screenshot',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function defaults(): array
    {
        return [
            'strip_screenshot' => '1',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'url' => $schema->string()->description('Example: https://example.com.')->required(),
            'desktop_preset' => $schema->boolean(),
            'no_local_resolve' => $schema->boolean(),
            'strip_screenshot' => $schema->boolean()->description('Drop the final-screenshot audit\'s embedded base64 PNG (details.data), which otherwise dwarfs the score/metric data in the report and cannot be rendered inline anyway. This tool sends 1 when it is omitted.'),
        ];
    }
}
