#!/bin/bash
set -e
cd ~/project

# Generated values for a compose file that cannot generate any of them, written
# where `docker compose` reads variables from: the project's .env. The admin
# login (ADMIN_EMAIL / ADMIN_PASSWORD) is the engine's (`credentials:` in
# panelalpha.yaml), read by the install service from
# ~/.panelalpha/app-credentials.env.
#
# The secrets live outside the checkout, in $HOME. ~/project does not survive a
# deploy -- the clone empties it first -- while the MySQL volume and the
# /etc/solidinvoice volume (which holds SolidInvoice's own secret vault) do. A
# database password regenerated on redeploy would be one the database no longer
# accepts.
# Generated once, reused for the life of the account.
STORE="${HOME}/.panelalpha/solidinvoice.env"

if [ ! -f "${STORE}" ]; then
    mkdir -p "$(dirname "${STORE}")"
    chmod 700 "$(dirname "${STORE}")"
    umask 077
    cat > "${STORE}" <<EOF
# Generated by the PanelAlpha SolidInvoice recipe. Kept out of ~/project,
# which is emptied and re-cloned on every deploy.
#
# The repository's own docker-compose.yml runs MySQL with
# MYSQL_ALLOW_EMPTY_PASSWORD: 1 -- upstream's docker.md flags that as
# "simplicity" and tells you to set a password before production. This is
# production.
DB_ROOT_PASSWORD=$(openssl rand -hex 16)
DB_PASSWORD=$(openssl rand -hex 16)
EOF
    chmod 600 "${STORE}"
fi

# :latest, deliberately. SolidInvoice publishes one tag per release plus
# :latest, and nothing in the checkout names a published tag: composer.json
# says 3.0.1 on the 3.1.x branch, SolidInvoiceCoreBundle::VERSION says
# 3.1.0-dev, and neither is a tag on Docker Hub. A pull that 404s is a deploy
# that dies at `up -d`.
cat > .env <<EOF
SOLIDINVOICE_IMAGE=solidinvoice/solidinvoice:latest
EOF
# Older stores also hold ADMIN_PASSWORD; it stays out of .env.
grep -v '^ADMIN_' "${STORE}" >> .env || true
chmod 600 .env
