#!/bin/bash
set -euo pipefail

USERCONF="/etc/sftp/logins.conf"
SSH_KEYS_CONF="/etc/ssh/sshd_config.d/user_keys.conf"

mkdir -p /etc/ssh/sshd_config.d
if ! grep -q '^Include /etc/ssh/sshd_config.d/\*\.conf' /etc/ssh/sshd_config; then
    echo 'Include /etc/ssh/sshd_config.d/*.conf' >> /etc/ssh/sshd_config
fi

declare -A conf_users conf_uids conf_gids conf_homes conf_pass conf_keys

while IFS=: read -r user pass uid gid home pubkey; do
    [[ -z "$user" ]] && continue
    conf_users["$user"]=1
    conf_uids["$user"]=$uid
    conf_gids["$user"]=$gid
    conf_homes["$user"]=$home
    conf_pass["$user"]=$pass
    conf_keys["$user"]=$pubkey
done < "$USERCONF"

# Protected accounts (in case some UID >= 1000 is special)
PROTECTED_USERS=("nobody")

# Delete system users not in config (UID >= 1000)
for sysuser in $(awk -F: '$3 >= 1000 {print $1}' /etc/passwd); do
    if [[ -z "${conf_users[$sysuser]:-}" ]]; then
        if [[ ! " ${PROTECTED_USERS[*]} " =~ " $sysuser " ]]; then
            echo "Removing user $sysuser"
            userdel -r "$sysuser" || true
        fi
    fi
done

# Add or update users
for user in "${!conf_users[@]}"; do
    uid=${conf_uids[$user]}
    gid=${conf_gids[$user]}
    home=${conf_homes[$user]}
    pass=${conf_pass[$user]}
    pubkey=${conf_keys[$user]}

    # Create group if missing
    if ! getent group "$gid" >/dev/null; then
        groupadd -g "$gid" "$user" 2>/dev/null || true
    fi

    if id "$user" &>/dev/null; then
        echo "Updating user $user"
        usermod -u "$uid" -g "$gid" -d "$home" "$user" || true
    else
        echo "Creating user $user"
        useradd -M -u "$uid" -g "$gid" -d "$home" -s /usr/sbin/nologin --non-unique "$user"
    fi

    # Password
    if [[ -n "$pass" ]]; then
        echo "$user:$pass" | chpasswd -e
    else
        # Disable password login, but keep account usable for keys
        usermod -p '*' "$user"
    fi

done

# Generate sshd_config.d file for public keys
echo "# Auto-generated by sync-logins" > "$SSH_KEYS_CONF"
for user in "${!conf_users[@]}"; do
    pubkey=${conf_keys[$user]}
    [[ -z "$pubkey" ]] && continue
    cat >> "$SSH_KEYS_CONF" <<EOF
Match User $user
    AuthorizedKeysCommand /bin/echo "$pubkey"
    AuthorizedKeysCommandUser nobody
EOF
done

# Reload sshd to apply new users/keys, if running. Only the listener: every
# open connection is an sshd too -- on a host with 2222 open to the internet
# there always are some -- and `kill -HUP "$(pidof sshd)"` passed all of them as
# one argument, failed, and left new keys unread until a restart (engine#243).
listener=""
for pid in $(pidof sshd 2>/dev/null); do
    ppid=$(awk '{print $4}' "/proc/$pid/stat" 2>/dev/null) || continue
    if [ "$(cat "/proc/$ppid/comm" 2>/dev/null)" != "sshd" ]; then
        listener=$pid
        break
    fi
done
if [ -n "$listener" ]; then
    echo "Reloading sshd..."
    kill -HUP "$listener"
else
    echo "sshd not running yet, skipping reload"
fi